"""
Version Injection Utility for CasareRPA Installers.

Reads version from pyproject.toml and injects into:
- file_version_info.txt (PyInstaller)
- NSIS scripts (!define VERSION)
- Python __version__ attribute

Usage:
    from deploy.installer.version import get_version, inject_version_info
"""

from __future__ import annotations

import re
import sys
from pathlib import Path
from typing import NamedTuple

if sys.version_info >= (3, 11):
    import tomllib
else:
    try:
        import tomli as tomllib
    except ImportError:
        tomllib = None


class VersionInfo(NamedTuple):
    """Parsed version information."""

    major: int
    minor: int
    patch: int
    build: int = 0

    @property
    def tuple(self) -> tuple[int, int, int, int]:
        return (self.major, self.minor, self.patch, self.build)

    @property
    def string(self) -> str:
        return f"{self.major}.{self.minor}.{self.patch}"

    @property
    def full_string(self) -> str:
        return f"{self.major}.{self.minor}.{self.patch}.{self.build}"

    @classmethod
    def parse(cls, version_str: str) -> "VersionInfo":
        """Parse version string like '3.0.0' or '3.0.0.1'."""
        parts = version_str.strip().split(".")
        if len(parts) < 3:
            raise ValueError(f"Invalid version format: {version_str}")

        return cls(
            major=int(parts[0]),
            minor=int(parts[1]),
            patch=int(parts[2]),
            build=int(parts[3]) if len(parts) > 3 else 0,
        )


def get_project_root() -> Path:
    """Get project root directory."""
    current = Path(__file__).resolve()
    for parent in current.parents:
        if (parent / "pyproject.toml").exists():
            return parent
    raise FileNotFoundError("Could not find project root (no pyproject.toml)")


def get_version() -> VersionInfo:
    """Read version from pyproject.toml."""
    project_root = get_project_root()
    pyproject_path = project_root / "pyproject.toml"

    if tomllib is None:
        # Fallback: regex extraction
        content = pyproject_path.read_text(encoding="utf-8")
        match = re.search(r'version\s*=\s*"([^"]+)"', content)
        if match:
            return VersionInfo.parse(match.group(1))
        raise ValueError("Could not extract version from pyproject.toml")

    with open(pyproject_path, "rb") as f:
        data = tomllib.load(f)

    version_str = data.get("project", {}).get("version", "0.0.0")
    return VersionInfo.parse(version_str)


def generate_file_version_info(version: VersionInfo, output_path: Path | None = None) -> str:
    """Generate file_version_info.txt content for PyInstaller."""
    content = f"""# UTF-8
#
# Windows version info file for CasareRPA executable.
# Auto-generated by deploy/installer/version.py
#
# For more info see:
# https://pyinstaller.org/en/stable/usage.html#capturing-windows-version-data

VSVersionInfo(
  ffi=FixedFileInfo(
    # filevers and prodvers must be tuples of 4 16-bit integers
    filevers={version.tuple},
    prodvers={version.tuple},
    # Contains a bitmask that specifies the valid bits 'flags'
    mask=0x3f,
    # Contains a bitmask that specifies the Boolean attributes of the file.
    flags=0x0,
    # The operating system for which this file was designed.
    # 0x40004 - NT and target Win32 API
    OS=0x40004,
    # The general type of file.
    # 0x1 - the file is an application.
    fileType=0x1,
    # The function of the file.
    # 0x0 - not applicable
    subtype=0x0,
    # Creation date and time stamp.
    date=(0, 0)
  ),
  kids=[
    StringFileInfo(
      [
        StringTable(
          u'040904B0',  # Language and codepage (US English, Unicode)
          [
            StringStruct(u'CompanyName', u'CasareRPA Team'),
            StringStruct(u'FileDescription', u'CasareRPA - Windows Desktop RPA Platform'),
            StringStruct(u'FileVersion', u'{version.full_string}'),
            StringStruct(u'InternalName', u'CasareRPA'),
            StringStruct(u'LegalCopyright', u'Copyright (c) 2025 CasareRPA Team. MIT License.'),
            StringStruct(u'OriginalFilename', u'CasareRPA.exe'),
            StringStruct(u'ProductName', u'CasareRPA'),
            StringStruct(u'ProductVersion', u'{version.string}'),
            StringStruct(u'Comments', u'Visual node-based RPA workflow editor and robot agent'),
          ]
        )
      ]
    ),
    VarFileInfo([VarStruct(u'Translation', [1033, 1200])])
  ]
)
"""
    if output_path:
        output_path.write_text(content, encoding="utf-8")
    return content


def inject_nsis_version(nsi_file: Path, version: VersionInfo) -> None:
    """Update VERSION define in NSIS script."""
    content = nsi_file.read_text(encoding="utf-8")

    # Replace !define PRODUCT_VERSION "x.x.x" pattern
    pattern = r'(!define\s+PRODUCT_VERSION\s+")[^"]*(")'
    replacement = f"\\g<1>{version.string}\\g<2>"
    new_content = re.sub(pattern, replacement, content)

    if new_content != content:
        nsi_file.write_text(new_content, encoding="utf-8")


def inject_spec_version(spec_file: Path, version: VersionInfo) -> None:
    """Update APP_VERSION in PyInstaller spec file."""
    content = spec_file.read_text(encoding="utf-8")

    # Replace APP_VERSION = "x.x.x" pattern
    pattern = r'(APP_VERSION\s*=\s*")[^"]*(")'
    replacement = f"\\g<1>{version.string}\\g<2>"
    new_content = re.sub(pattern, replacement, content)

    if new_content != content:
        spec_file.write_text(new_content, encoding="utf-8")


def inject_all_versions() -> VersionInfo:
    """Inject version into all installer files."""
    version = get_version()
    installer_dir = Path(__file__).parent

    # Update file_version_info.txt
    generate_file_version_info(version, installer_dir / "file_version_info.txt")

    # Update NSIS scripts
    for nsi_file in installer_dir.glob("*.nsi"):
        inject_nsis_version(nsi_file, version)

    # Update spec files
    for spec_file in installer_dir.glob("*.spec"):
        inject_spec_version(spec_file, version)

    return version


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Version injection utility")
    parser.add_argument("--inject", action="store_true", help="Inject version into all files")
    parser.add_argument("--show", action="store_true", help="Show current version")
    args = parser.parse_args()

    if args.inject:
        ver = inject_all_versions()
        print(f"Injected version {ver.string} into all installer files")
    elif args.show:
        ver = get_version()
        print(f"Version: {ver.string}")
        print(f"Full: {ver.full_string}")
        print(f"Tuple: {ver.tuple}")
    else:
        parser.print_help()
