"""
Visual Nodes - Data Operations
"""

from casare_rpa.presentation.canvas.visual_nodes.data_operations.nodes import (
    VisualComparisonNode,
    # Data operations
    VisualConcatenateNode,
    VisualCreateDictNode,
    VisualCreateListNode,
    # Dict operations
    VisualDictGetNode,
    VisualDictHasKeyNode,
    VisualDictItemsNode,
    VisualDictKeysNode,
    VisualDictMergeNode,
    VisualDictRemoveNode,
    VisualDictSetNode,
    VisualDictToJsonNode,
    VisualDictValuesNode,
    VisualFilterBySimilarityNode,
    VisualFormatStringNode,
    VisualFuzzyStringMatchNode,
    VisualGetPropertyNode,
    VisualJsonParseNode,
    VisualListAppendNode,
    VisualListContainsNode,
    VisualListFilterNode,
    VisualListFlattenNode,
    VisualListGetItemNode,
    VisualListJoinNode,
    # List operations
    VisualListLengthNode,
    VisualListMapNode,
    VisualListReduceNode,
    VisualListReverseNode,
    VisualListSliceNode,
    VisualListSortNode,
    VisualListUniqueNode,
    VisualMathOperationNode,
    VisualRegexMatchNode,
    VisualRegexReplaceNode,
)

__all__ = [
    # Data operations
    "VisualConcatenateNode",
    "VisualFormatStringNode",
    "VisualRegexMatchNode",
    "VisualRegexReplaceNode",
    "VisualFuzzyStringMatchNode",
    "VisualFilterBySimilarityNode",
    "VisualMathOperationNode",
    "VisualComparisonNode",
    "VisualCreateListNode",
    "VisualListGetItemNode",
    "VisualJsonParseNode",
    "VisualGetPropertyNode",
    # List operations
    "VisualListLengthNode",
    "VisualListAppendNode",
    "VisualListContainsNode",
    "VisualListSliceNode",
    "VisualListJoinNode",
    "VisualListSortNode",
    "VisualListReverseNode",
    "VisualListUniqueNode",
    "VisualListFilterNode",
    "VisualListMapNode",
    "VisualListReduceNode",
    "VisualListFlattenNode",
    # Dict operations
    "VisualDictGetNode",
    "VisualDictSetNode",
    "VisualDictRemoveNode",
    "VisualDictMergeNode",
    "VisualDictKeysNode",
    "VisualDictValuesNode",
    "VisualDictHasKeyNode",
    "VisualCreateDictNode",
    "VisualDictToJsonNode",
    "VisualDictItemsNode",
]
