"""Visual nodes for CAPTCHA solving category."""

from casare_rpa.domain.value_objects.types import DataType
from casare_rpa.presentation.canvas.visual_nodes.base_visual_node import VisualNode


class VisualDetectCaptchaNode(VisualNode):
    """
    Visual representation of DetectCaptchaNode.

    Detect if a CAPTCHA challenge is visible on the page.
    """

    __identifier__ = "casare_rpa.browser"
    NODE_NAME = "Detect CAPTCHA"
    NODE_CATEGORY = "browser/captcha"
    CASARE_NODE_CLASS = "DetectCaptchaNode"

    def __init__(self) -> None:
        """Initialize detect captcha node."""
        super().__init__()
        # Widgets auto-generated by @properties decorator

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("page", DataType.PAGE)
        self.add_exec_output("exec_out")
        self.add_typed_output("page", DataType.PAGE)
        self.add_typed_output("captcha_detected", DataType.BOOLEAN)
        self.add_typed_output("captcha_type", DataType.STRING)
        self.add_typed_output("sitekey", DataType.STRING)
        self.add_typed_output("page_url", DataType.STRING)


class VisualSolveCaptchaNode(VisualNode):
    """
    Visual representation of SolveCaptchaNode.

    Solve reCAPTCHA using 2Captcha API service.
    """

    __identifier__ = "casare_rpa.browser"
    NODE_NAME = "Solve CAPTCHA (2Captcha)"
    NODE_CATEGORY = "browser/captcha"
    CASARE_NODE_CLASS = "SolveCaptchaNode"

    def __init__(self) -> None:
        """Initialize solve captcha node."""
        super().__init__()
        # Widgets auto-generated by @properties decorator

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("page", DataType.PAGE)
        self.add_typed_input("sitekey", DataType.STRING)
        self.add_typed_input("page_url", DataType.STRING)
        self.add_exec_output("exec_out")
        self.add_typed_output("page", DataType.PAGE)
        self.add_typed_output("solved", DataType.BOOLEAN)
        self.add_typed_output("token", DataType.STRING)
        self.add_typed_output("cost", DataType.FLOAT)


class VisualSolveCaptchaAINode(VisualNode):
    """
    Visual representation of SolveCaptchaAINode.

    Solve reCAPTCHA using AI vision models (Gemini, DeepSeek, etc.)
    Much faster than 2Captcha (~2-5 seconds).
    """

    __identifier__ = "casare_rpa.browser"
    NODE_NAME = "Solve CAPTCHA (AI)"
    NODE_CATEGORY = "browser/captcha"
    CASARE_NODE_CLASS = "SolveCaptchaAINode"

    def __init__(self) -> None:
        """Initialize AI captcha solver node."""
        super().__init__()
        # Widgets auto-generated by @properties decorator

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("page", DataType.PAGE)
        self.add_exec_output("exec_out")
        self.add_typed_output("page", DataType.PAGE)
        self.add_typed_output("solved", DataType.BOOLEAN)
        self.add_typed_output("attempts", DataType.INTEGER)
