"""
Visual node for Browser Evaluate - executes JavaScript in browser context.
"""

from casare_rpa.domain.value_objects.types import DataType
from casare_rpa.presentation.canvas.visual_nodes.base_visual_node import VisualNode


class VisualBrowserEvaluateNode(VisualNode):
    """
    Visual representation of BrowserEvaluateNode.

    Executes JavaScript code in the browser context and returns the result.
    Useful for custom DOM manipulation, data extraction, or interacting with
    page APIs that aren't covered by other nodes.
    """

    __identifier__ = "casare_rpa.browser"
    NODE_NAME = "Browser Evaluate"
    NODE_CATEGORY = "browser/interaction"
    CASARE_NODE_CLASS = "BrowserEvaluateNode"

    def __init__(self) -> None:
        """Initialize browser evaluate node."""
        super().__init__()
        # Widgets auto-generated by @properties decorator on BrowserEvaluateNode

    def setup_ports(self) -> None:
        """Setup ports for JavaScript evaluation."""
        # Execution flow
        self.add_exec_input("exec_in")
        self.add_exec_output("exec_out")

        # Input ports
        self.add_typed_input("page", DataType.PAGE)
        self.add_typed_input("script", DataType.STRING)
        self.add_typed_input("args", DataType.LIST)  # Optional arguments to pass to script

        # Output ports
        self.add_typed_output("page", DataType.PAGE)
        self.add_typed_output("result", DataType.ANY)  # JavaScript evaluation result


__all__ = [
    "VisualBrowserEvaluateNode",
]
