"""Visual nodes for browser category.

Widget Auto-Generation:
-----------------------
Visual nodes automatically inherit widgets from their domain node's @node_schema
decorator via the __node_schema__ attribute (defined in casare_rpa.domain.decorators).

When a VisualNode is instantiated:
1. BaseVisualNode.__init__() checks if domain_node_class has __node_schema__
2. If found, widgets are auto-generated from PropertyDef declarations
3. Manual widget creation in __init__() should be AVOIDED to prevent duplicates

Nodes with manual widgets:
- GoToURLNode, GoBackNode, GoForwardNode, RefreshPageNode (navigation category)
- ClickElementNode, TypeTextNode, SelectDropdownNode (interaction category)
- ExtractTextNode, GetAttributeNode (data extraction category)
- ScreenshotNode, WaitNode, WaitForElementNode, WaitForNavigationNode (utility category)

These nodes still use manual widgets because their domain nodes haven't been
migrated to @node_schema yet. Once migrated, remove manual widgets from __init__().
"""

from casare_rpa.domain.value_objects.types import DataType
from casare_rpa.presentation.canvas.visual_nodes.base_visual_node import VisualNode


class VisualLaunchBrowserNode(VisualNode):
    """Visual representation of LaunchBrowserNode."""

    __identifier__ = "casare_rpa.browser"
    NODE_NAME = "Launch Browser"
    NODE_CATEGORY = "browser"

    def __init__(self) -> None:
        """Initialize launch browser node."""
        super().__init__()
        # Widgets auto-generated by @node_schema decorator

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("url", DataType.STRING)
        self.add_exec_output("exec_out")
        self.add_typed_output("browser", DataType.BROWSER)
        self.add_typed_output("page", DataType.PAGE)


class VisualCloseBrowserNode(VisualNode):
    """Visual representation of CloseBrowserNode."""

    __identifier__ = "casare_rpa.browser"
    NODE_NAME = "Close Browser"
    NODE_CATEGORY = "browser"

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("browser", DataType.BROWSER)
        self.add_exec_output("exec_out")


class VisualNewTabNode(VisualNode):
    """Visual representation of NewTabNode."""

    __identifier__ = "casare_rpa.browser"
    NODE_NAME = "New Tab"
    NODE_CATEGORY = "browser"

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("browser", DataType.BROWSER)
        self.add_exec_output("exec_out")
        self.add_typed_output("page", DataType.PAGE)


class VisualGetAllImagesNode(VisualNode):
    """Visual representation of GetAllImagesNode."""

    __identifier__ = "casare_rpa.browser"
    NODE_NAME = "Get All Images"
    NODE_CATEGORY = "browser"

    def __init__(self) -> None:
        """Initialize get all images node."""
        super().__init__()
        # Widgets auto-generated by @node_schema decorator

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_exec_output("exec_out")
        self.add_typed_output("images", DataType.LIST)
        self.add_typed_output("count", DataType.INTEGER)


class VisualDownloadFileNode(VisualNode):
    """Visual representation of DownloadFileNode."""

    __identifier__ = "casare_rpa.browser"
    NODE_NAME = "Download File"
    NODE_CATEGORY = "browser"

    def __init__(self) -> None:
        """Initialize download file node."""
        super().__init__()
        # Widgets auto-generated by @node_schema decorator

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("url", DataType.STRING)
        self.add_typed_input("filename", DataType.STRING)
        self.add_exec_output("exec_out")
        self.add_typed_output("path", DataType.STRING)
        self.add_typed_output("size", DataType.INTEGER)
        self.add_typed_output("success", DataType.BOOLEAN)


# Navigation Nodes


class VisualGoToURLNode(VisualNode):
    """Visual representation of GoToURLNode."""

    __identifier__ = "casare_rpa.navigation"
    NODE_NAME = "Go To URL"
    NODE_CATEGORY = "browser"

    def __init__(self) -> None:
        """Initialize go to URL node."""
        super().__init__()
        # Widgets auto-generated by @node_schema decorator

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("page", DataType.PAGE)
        self.add_typed_input("url", DataType.STRING)
        self.add_exec_output("exec_out")
        self.add_typed_output("page", DataType.PAGE)


class VisualGoBackNode(VisualNode):
    """Visual representation of GoBackNode."""

    __identifier__ = "casare_rpa.navigation"
    NODE_NAME = "Go Back"
    NODE_CATEGORY = "browser"

    def __init__(self) -> None:
        """Initialize go back node."""
        super().__init__()
        # Widgets auto-generated by @node_schema decorator

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("page", DataType.PAGE)
        self.add_exec_output("exec_out")
        self.add_typed_output("page", DataType.PAGE)


class VisualGoForwardNode(VisualNode):
    """Visual representation of GoForwardNode."""

    __identifier__ = "casare_rpa.navigation"
    NODE_NAME = "Go Forward"
    NODE_CATEGORY = "browser"

    def __init__(self) -> None:
        """Initialize go forward node."""
        super().__init__()
        # Widgets auto-generated by @node_schema decorator

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("page", DataType.PAGE)
        self.add_exec_output("exec_out")
        self.add_typed_output("page", DataType.PAGE)


class VisualRefreshPageNode(VisualNode):
    """Visual representation of RefreshPageNode."""

    __identifier__ = "casare_rpa.navigation"
    NODE_NAME = "Refresh Page"
    NODE_CATEGORY = "browser"

    def __init__(self) -> None:
        """Initialize refresh page node."""
        super().__init__()
        # Widgets auto-generated by @node_schema decorator

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("page", DataType.PAGE)
        self.add_exec_output("exec_out")
        self.add_typed_output("page", DataType.PAGE)


# Interaction Nodes


class VisualClickElementNode(VisualNode):
    """Visual representation of ClickElementNode."""

    __identifier__ = "casare_rpa.interaction"
    NODE_NAME = "Click Element"
    NODE_CATEGORY = "browser"

    def __init__(self) -> None:
        """Initialize click element node."""
        super().__init__()
        # Widgets auto-generated by @node_schema decorator

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("page", DataType.PAGE)
        self.add_typed_input("selector", DataType.STRING)
        self.add_exec_output("exec_out")
        self.add_typed_output("page", DataType.PAGE)


class VisualTypeTextNode(VisualNode):
    """Visual representation of TypeTextNode."""

    __identifier__ = "casare_rpa.interaction"
    NODE_NAME = "Type Text"
    NODE_CATEGORY = "browser"

    def __init__(self) -> None:
        """Initialize type text node."""
        super().__init__()
        # Widgets auto-generated by @node_schema decorator

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("page", DataType.PAGE)
        self.add_typed_input("selector", DataType.STRING)
        self.add_typed_input("text", DataType.STRING)
        self.add_exec_output("exec_out")
        self.add_typed_output("page", DataType.PAGE)


class VisualSelectDropdownNode(VisualNode):
    """Visual representation of SelectDropdownNode."""

    __identifier__ = "casare_rpa.interaction"
    NODE_NAME = "Select Dropdown"
    NODE_CATEGORY = "browser"

    def __init__(self) -> None:
        """Initialize select dropdown node."""
        super().__init__()
        # Widgets auto-generated by @node_schema decorator

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("page", DataType.PAGE)
        self.add_typed_input("selector", DataType.STRING)
        self.add_typed_input("value", DataType.STRING)
        self.add_exec_output("exec_out")
        self.add_typed_output("page", DataType.PAGE)


# Data Extraction Nodes


class VisualExtractTextNode(VisualNode):
    """Visual representation of ExtractTextNode."""

    __identifier__ = "casare_rpa.data"
    NODE_NAME = "Extract Text"
    NODE_CATEGORY = "browser"

    def __init__(self) -> None:
        """Initialize extract text node."""
        super().__init__()
        # Widgets auto-generated by @node_schema decorator

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("page", DataType.PAGE)
        self.add_typed_input("selector", DataType.STRING)
        self.add_exec_output("exec_out")
        self.add_typed_output("page", DataType.PAGE)
        self.add_typed_output("text", DataType.STRING)


class VisualGetAttributeNode(VisualNode):
    """Visual representation of GetAttributeNode."""

    __identifier__ = "casare_rpa.data"
    NODE_NAME = "Get Attribute"
    NODE_CATEGORY = "browser"

    def __init__(self) -> None:
        """Initialize get attribute node."""
        super().__init__()
        # Widgets auto-generated by @node_schema decorator

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("page", DataType.PAGE)
        self.add_typed_input("selector", DataType.STRING)
        self.add_typed_input("attribute", DataType.STRING)
        self.add_exec_output("exec_out")
        self.add_typed_output("page", DataType.PAGE)
        self.add_typed_output("value", DataType.STRING)


class VisualScreenshotNode(VisualNode):
    """Visual representation of ScreenshotNode."""

    __identifier__ = "casare_rpa.data"
    NODE_NAME = "Screenshot"
    NODE_CATEGORY = "browser"

    def __init__(self) -> None:
        """Initialize screenshot node."""
        super().__init__()
        # Widgets auto-generated by @node_schema decorator

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("page", DataType.PAGE)
        self.add_typed_input("file_path", DataType.STRING)
        self.add_exec_output("exec_out")
        self.add_typed_output("page", DataType.PAGE)


# Wait Nodes


class VisualWaitNode(VisualNode):
    """Visual representation of WaitNode."""

    __identifier__ = "casare_rpa.wait"
    NODE_NAME = "Wait"
    NODE_CATEGORY = "browser"

    def __init__(self) -> None:
        """Initialize wait node."""
        super().__init__()
        # Widget auto-generated from @node_schema decorator on WaitNode

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        # duration is a config property, not a data port - auto-generated as widget
        self.add_exec_output("exec_out")


class VisualWaitForElementNode(VisualNode):
    """Visual representation of WaitForElementNode."""

    __identifier__ = "casare_rpa.wait"
    NODE_NAME = "Wait For Element"
    NODE_CATEGORY = "browser"

    def __init__(self) -> None:
        """Initialize wait for element node."""
        super().__init__()
        # Widgets auto-generated by @node_schema decorator

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("page", DataType.PAGE)
        self.add_typed_input("selector", DataType.STRING)
        self.add_exec_output("exec_out")
        self.add_typed_output("page", DataType.PAGE)
        self.add_typed_output("found", DataType.BOOLEAN)


class VisualWaitForNavigationNode(VisualNode):
    """Visual representation of WaitForNavigationNode."""

    __identifier__ = "casare_rpa.wait"
    NODE_NAME = "Wait For Navigation"
    NODE_CATEGORY = "browser"

    def __init__(self) -> None:
        """Initialize wait for navigation node."""
        super().__init__()
        # Widgets auto-generated by @node_schema decorator

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("page", DataType.PAGE)
        self.add_exec_output("exec_out")
        self.add_typed_output("page", DataType.PAGE)


# Variable Nodes
