"""Visual nodes for browser category.

Widget Auto-Generation:
-----------------------
Visual nodes automatically inherit widgets from their domain node's @properties
decorator via the __node_schema__ attribute (defined in casare_rpa.domain.decorators).

When a VisualNode is instantiated:
1. BaseVisualNode.__init__() checks if domain_node_class has __node_schema__
2. If found, widgets are auto-generated from PropertyDef declarations
3. Manual widget creation in __init__() should be AVOIDED to prevent duplicates

Nodes with manual widgets:
- GoToURLNode, GoBackNode, GoForwardNode, RefreshPageNode (navigation category)
- ClickElementNode, TypeTextNode, SelectDropdownNode (interaction category)
- ExtractTextNode, GetAttributeNode (data extraction category)
- ScreenshotNode, WaitNode, WaitForElementNode, WaitForNavigationNode (utility category)

These nodes still use manual widgets because their domain nodes haven't been
migrated to @properties yet. Once migrated, remove manual widgets from __init__().
"""

from casare_rpa.domain.value_objects.types import DataType
from casare_rpa.presentation.canvas.visual_nodes.base_visual_node import VisualNode
from casare_rpa.presentation.canvas.graph.node_widgets import NodeFilePathWidget


def _replace_widget(node: VisualNode, widget) -> None:
    """
    Replace auto-generated widget with custom widget.

    If a property already exists (from @properties auto-generation),
    remove it first to avoid NodePropertyError conflicts.

    Args:
        node: The visual node
        widget: The custom widget to add (NodeFilePathWidget or NodeDirectoryPathWidget)
    """
    prop_name = widget._name  # NodeBaseWidget stores name as _name
    # Remove existing property if it was auto-generated from schema
    if hasattr(node, "model") and prop_name in node.model.custom_properties:
        del node.model.custom_properties[prop_name]
        # Also remove from widgets dict if present
        if hasattr(node, "_widgets") and prop_name in node._widgets:
            del node._widgets[prop_name]
    # Now safely add our custom widget
    node.add_custom_widget(widget)
    widget.setParentItem(node.view)


class VisualLaunchBrowserNode(VisualNode):
    """Visual representation of LaunchBrowserNode."""

    __identifier__ = "casare_rpa.browser"
    NODE_NAME = "Launch Browser"
    NODE_CATEGORY = "browser/launch"
    CASARE_NODE_CLASS = "LaunchBrowserNode"

    def __init__(self) -> None:
        """Initialize launch browser node."""
        super().__init__()
        # Widgets auto-generated by @properties decorator

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("url", DataType.STRING)
        self.add_exec_output("exec_out")
        self.add_typed_output("browser", DataType.BROWSER)
        self.add_typed_output("page", DataType.PAGE)
        self.add_typed_output("window", DataType.ANY)


class VisualCloseBrowserNode(VisualNode):
    """Visual representation of CloseBrowserNode."""

    __identifier__ = "casare_rpa.browser"
    NODE_NAME = "Close Browser"
    NODE_CATEGORY = "browser/launch"
    CASARE_NODE_CLASS = "CloseBrowserNode"

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("browser", DataType.BROWSER)
        self.add_exec_output("exec_out")


class VisualNewTabNode(VisualNode):
    """Visual representation of NewTabNode."""

    __identifier__ = "casare_rpa.browser"
    NODE_NAME = "New Tab"
    NODE_CATEGORY = "browser/navigation"
    CASARE_NODE_CLASS = "NewTabNode"

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("browser", DataType.BROWSER)
        self.add_exec_output("exec_out")
        self.add_typed_output("page", DataType.PAGE)


class VisualGetAllImagesNode(VisualNode):
    """Visual representation of GetAllImagesNode."""

    __identifier__ = "casare_rpa.browser"
    NODE_NAME = "Get All Images"
    NODE_CATEGORY = "browser/data"
    CASARE_NODE_CLASS = "GetAllImagesNode"

    def __init__(self) -> None:
        """Initialize get all images node."""
        super().__init__()
        # Widgets auto-generated by @properties decorator

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_exec_output("exec_out")
        self.add_typed_output("images", DataType.LIST)
        self.add_typed_output("count", DataType.INTEGER)


class VisualDownloadFileNode(VisualNode):
    """Visual representation of DownloadFileNode."""

    __identifier__ = "casare_rpa.browser"
    NODE_NAME = "Download File"
    NODE_CATEGORY = "browser/data"
    CASARE_NODE_CLASS = "DownloadFileNode"

    def __init__(self) -> None:
        """Initialize download file node."""
        super().__init__()
        # Widgets auto-generated by @properties decorator

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("url", DataType.STRING)
        self.add_typed_input("filename", DataType.STRING)
        self.add_exec_output("exec_out")
        self.add_typed_output("path", DataType.STRING)
        self.add_typed_output("size", DataType.INTEGER)
        self.add_typed_output("success", DataType.BOOLEAN)


# Navigation Nodes


class VisualGoToURLNode(VisualNode):
    """Visual representation of GoToURLNode."""

    __identifier__ = "casare_rpa.navigation"
    NODE_NAME = "Go To URL"
    NODE_CATEGORY = "browser/navigation"
    CASARE_NODE_CLASS = "GoToURLNode"

    def __init__(self) -> None:
        """Initialize go to URL node."""
        super().__init__()
        # Widgets auto-generated by @properties decorator

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("page", DataType.PAGE)
        self.add_typed_input("url", DataType.STRING)
        self.add_exec_output("exec_out")
        self.add_typed_output("page", DataType.PAGE)


class VisualGoBackNode(VisualNode):
    """Visual representation of GoBackNode."""

    __identifier__ = "casare_rpa.navigation"
    NODE_NAME = "Go Back"
    NODE_CATEGORY = "browser/navigation"
    CASARE_NODE_CLASS = "GoBackNode"

    def __init__(self) -> None:
        """Initialize go back node."""
        super().__init__()
        # Widgets auto-generated by @properties decorator

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("page", DataType.PAGE)
        self.add_exec_output("exec_out")
        self.add_typed_output("page", DataType.PAGE)


class VisualGoForwardNode(VisualNode):
    """Visual representation of GoForwardNode."""

    __identifier__ = "casare_rpa.navigation"
    NODE_NAME = "Go Forward"
    NODE_CATEGORY = "browser/navigation"
    CASARE_NODE_CLASS = "GoForwardNode"

    def __init__(self) -> None:
        """Initialize go forward node."""
        super().__init__()
        # Widgets auto-generated by @properties decorator

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("page", DataType.PAGE)
        self.add_exec_output("exec_out")
        self.add_typed_output("page", DataType.PAGE)


class VisualRefreshPageNode(VisualNode):
    """Visual representation of RefreshPageNode."""

    __identifier__ = "casare_rpa.navigation"
    NODE_NAME = "Refresh Page"
    NODE_CATEGORY = "browser/navigation"
    CASARE_NODE_CLASS = "RefreshPageNode"

    def __init__(self) -> None:
        """Initialize refresh page node."""
        super().__init__()
        # Widgets auto-generated by @properties decorator

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("page", DataType.PAGE)
        self.add_exec_output("exec_out")
        self.add_typed_output("page", DataType.PAGE)


# Interaction Nodes


class VisualClickElementNode(VisualNode):
    """Visual representation of ClickElementNode."""

    __identifier__ = "casare_rpa.interaction"
    NODE_NAME = "Click Element"
    NODE_CATEGORY = "browser/interaction"
    CASARE_NODE_CLASS = "ClickElementNode"

    def __init__(self) -> None:
        """Initialize click element node."""
        super().__init__()
        # Widgets auto-generated by @properties decorator

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("page", DataType.PAGE)
        self.add_typed_input("selector", DataType.STRING)
        self.add_exec_output("exec_out")
        self.add_typed_output("page", DataType.PAGE)


class VisualTypeTextNode(VisualNode):
    """Visual representation of TypeTextNode."""

    __identifier__ = "casare_rpa.interaction"
    NODE_NAME = "Type Text"
    NODE_CATEGORY = "browser/interaction"
    CASARE_NODE_CLASS = "TypeTextNode"

    def __init__(self) -> None:
        """Initialize type text node."""
        super().__init__()
        # Widgets auto-generated by @properties decorator

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("page", DataType.PAGE)
        self.add_typed_input("selector", DataType.STRING)
        self.add_typed_input("text", DataType.STRING)
        self.add_exec_output("exec_out")
        self.add_typed_output("page", DataType.PAGE)


class VisualSelectDropdownNode(VisualNode):
    """Visual representation of SelectDropdownNode."""

    __identifier__ = "casare_rpa.interaction"
    NODE_NAME = "Select Dropdown"
    NODE_CATEGORY = "browser/interaction"
    CASARE_NODE_CLASS = "SelectDropdownNode"

    def __init__(self) -> None:
        """Initialize select dropdown node."""
        super().__init__()
        # Widgets auto-generated by @properties decorator

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("page", DataType.PAGE)
        self.add_typed_input("selector", DataType.STRING)
        self.add_typed_input("value", DataType.STRING)
        self.add_exec_output("exec_out")
        self.add_typed_output("page", DataType.PAGE)


class VisualImageClickNode(VisualNode):
    """
    Visual representation of ImageClickNode.

    Clicks at a location found by image/template matching.
    Uses computer vision to find a template image on the page.
    """

    __identifier__ = "casare_rpa.interaction"
    NODE_NAME = "Image Click"
    NODE_CATEGORY = "browser/interaction"
    CASARE_NODE_CLASS = "ImageClickNode"

    def __init__(self) -> None:
        """Initialize image click node."""
        super().__init__()
        # Widgets auto-generated by @properties decorator

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("page", DataType.PAGE)
        self.add_exec_output("exec_out")
        self.add_typed_output("page", DataType.PAGE)


class VisualPressKeyNode(VisualNode):
    """
    Visual representation of PressKeyNode.

    Presses a keyboard key on the browser page using Playwright.
    Useful for pressing keys like Escape to dismiss modals, Enter to submit,
    Tab to navigate, or any special keys.
    """

    __identifier__ = "casare_rpa.interaction"
    NODE_NAME = "Press Key"
    NODE_CATEGORY = "browser/interaction"
    CASARE_NODE_CLASS = "PressKeyNode"

    def __init__(self) -> None:
        """Initialize press key node."""
        super().__init__()
        # Widgets auto-generated by @properties decorator

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("page", DataType.PAGE)
        self.add_exec_output("exec_out")
        self.add_typed_output("page", DataType.PAGE)


# Data Extraction Nodes


class VisualExtractTextNode(VisualNode):
    """Visual representation of ExtractTextNode."""

    __identifier__ = "casare_rpa.data"
    NODE_NAME = "Extract Text"
    NODE_CATEGORY = "browser/data"
    CASARE_NODE_CLASS = "ExtractTextNode"

    def __init__(self) -> None:
        """Initialize extract text node."""
        super().__init__()
        # Widgets auto-generated by @properties decorator

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("page", DataType.PAGE)
        self.add_typed_input("selector", DataType.STRING)
        self.add_exec_output("exec_out")
        self.add_typed_output("page", DataType.PAGE)
        self.add_typed_output("text", DataType.STRING)


class VisualGetAttributeNode(VisualNode):
    """Visual representation of GetAttributeNode."""

    __identifier__ = "casare_rpa.data"
    NODE_NAME = "Get Attribute"
    NODE_CATEGORY = "browser/data"
    CASARE_NODE_CLASS = "GetAttributeNode"

    def __init__(self) -> None:
        """Initialize get attribute node."""
        super().__init__()
        # Widgets auto-generated by @properties decorator

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("page", DataType.PAGE)
        self.add_typed_input("selector", DataType.STRING)
        self.add_typed_input("attribute", DataType.STRING)
        self.add_exec_output("exec_out")
        self.add_typed_output("page", DataType.PAGE)
        self.add_typed_output("value", DataType.STRING)


class VisualScreenshotNode(VisualNode):
    """Visual representation of ScreenshotNode."""

    __identifier__ = "casare_rpa.data"
    NODE_NAME = "Screenshot"
    NODE_CATEGORY = "browser/data"
    CASARE_NODE_CLASS = "ScreenshotNode"

    def __init__(self) -> None:
        """Initialize screenshot node."""
        super().__init__()
        _replace_widget(
            self,
            NodeFilePathWidget(
                name="file_path",
                label="Save Path",
                file_filter="Image Files (*.png *.jpg *.jpeg);;All Files (*.*)",
                placeholder="Select save location...",
            ),
        )

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("page", DataType.PAGE)
        self.add_typed_input("file_path", DataType.STRING)
        self.add_exec_output("exec_out")
        self.add_typed_output("page", DataType.PAGE)


# Wait Nodes


class VisualWaitNode(VisualNode):
    """Visual representation of WaitNode."""

    __identifier__ = "casare_rpa.wait"
    NODE_NAME = "Wait"
    NODE_CATEGORY = "browser/wait"
    CASARE_NODE_CLASS = "WaitNode"

    def __init__(self) -> None:
        """Initialize wait node."""
        super().__init__()
        # Widget auto-generated from @properties decorator on WaitNode

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        # duration is a config property, not a data port - auto-generated as widget
        self.add_exec_output("exec_out")


class VisualWaitForElementNode(VisualNode):
    """Visual representation of WaitForElementNode."""

    __identifier__ = "casare_rpa.wait"
    NODE_NAME = "Wait For Element"
    NODE_CATEGORY = "browser/wait"
    CASARE_NODE_CLASS = "WaitForElementNode"

    def __init__(self) -> None:
        """Initialize wait for element node."""
        super().__init__()
        # Widgets auto-generated by @properties decorator

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("page", DataType.PAGE)
        self.add_typed_input("selector", DataType.STRING)
        self.add_exec_output("exec_out")
        self.add_typed_output("page", DataType.PAGE)
        self.add_typed_output("found", DataType.BOOLEAN)


class VisualWaitForNavigationNode(VisualNode):
    """Visual representation of WaitForNavigationNode."""

    __identifier__ = "casare_rpa.wait"
    NODE_NAME = "Wait For Navigation"
    NODE_CATEGORY = "browser/wait"
    CASARE_NODE_CLASS = "WaitForNavigationNode"

    def __init__(self) -> None:
        """Initialize wait for navigation node."""
        super().__init__()
        # Widgets auto-generated by @properties decorator

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("page", DataType.PAGE)
        self.add_exec_output("exec_out")
        self.add_typed_output("page", DataType.PAGE)


# Table Scraping Nodes


class VisualTableScraperNode(VisualNode):
    """
    Visual representation of TableScraperNode.

    Extracts structured data from HTML tables and converts to various formats.
    """

    __identifier__ = "casare_rpa.browser"
    NODE_NAME = "Table Scraper"
    NODE_CATEGORY = "browser/data"
    CASARE_NODE_CLASS = "TableScraperNode"

    def __init__(self) -> None:
        """Initialize table scraper node."""
        super().__init__()
        # Widgets auto-generated by @properties decorator

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("page", DataType.PAGE)
        self.add_typed_input("table_selector", DataType.STRING)
        self.add_exec_output("exec_out")
        self.add_typed_output("data", DataType.ANY)
        self.add_typed_output("row_count", DataType.INTEGER)
        self.add_typed_output("headers", DataType.LIST)


# Form Nodes


class VisualFormFillerNode(VisualNode):
    """
    Visual representation of FormFillerNode.

    Fills form fields automatically based on a field mapping.
    """

    __identifier__ = "casare_rpa.browser"
    NODE_NAME = "Form Filler"
    NODE_CATEGORY = "browser/form"
    CASARE_NODE_CLASS = "FormFillerNode"

    def __init__(self) -> None:
        """Initialize form filler node."""
        super().__init__()
        # Widgets auto-generated by @properties decorator

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("page", DataType.PAGE)
        self.add_typed_input("field_mapping", DataType.OBJECT)
        self.add_typed_input("fields_in", DataType.LIST)  # From FormFieldNode chain
        self.add_exec_output("exec_out")
        self.add_typed_output("page", DataType.PAGE)
        self.add_typed_output("fields_filled", DataType.INTEGER)
        self.add_typed_output("form_data", DataType.OBJECT)


class VisualFormFieldNode(VisualNode):
    """
    Visual representation of FormFieldNode.

    Defines a form field for batch filling. Chain multiple FormFieldNodes
    together and connect to FormFillerNode for fast batch execution.
    """

    __identifier__ = "casare_rpa.browser"
    NODE_NAME = "Form Field"
    NODE_CATEGORY = "browser/form"
    CASARE_NODE_CLASS = "FormFieldNode"

    def __init__(self) -> None:
        """Initialize form field node."""
        super().__init__()
        # Widgets auto-generated by @properties decorator

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("page", DataType.PAGE)
        self.add_typed_input("fields_in", DataType.LIST)  # From previous FormFieldNode
        self.add_exec_output("exec_out")
        self.add_typed_output("page", DataType.PAGE)
        self.add_typed_output("fields_out", DataType.LIST)  # To next FormFieldNode or FormFiller
        self.add_typed_output("field", DataType.OBJECT)  # This field only


class VisualDetectFormsNode(VisualNode):
    """
    Visual representation of DetectFormsNode.

    Detects all forms and form fields on a web page.
    """

    __identifier__ = "casare_rpa.browser"
    NODE_NAME = "Detect Forms"
    NODE_CATEGORY = "browser/form"
    CASARE_NODE_CLASS = "DetectFormsNode"

    def __init__(self) -> None:
        """Initialize detect forms node."""
        super().__init__()
        # Widgets auto-generated by @properties decorator

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("page", DataType.PAGE)
        self.add_exec_output("exec_out")
        self.add_typed_output("page", DataType.PAGE)
        self.add_typed_output("forms", DataType.LIST)
        self.add_typed_output("form_count", DataType.INTEGER)
        self.add_typed_output("field_count", DataType.INTEGER)
        self.add_typed_output("fields", DataType.LIST)


# Variable Nodes
