"""Visual nodes for browser scripting category."""

from casare_rpa.domain.value_objects.types import DataType
from casare_rpa.presentation.canvas.visual_nodes.base_visual_node import VisualNode


class VisualBrowserRunScriptNode(VisualNode):
    """
    Visual representation of BrowserRunScriptNode.

    Execute custom Python script with browser access.
    """

    __identifier__ = "casare_rpa.browser"
    NODE_NAME = "Browser Script"
    NODE_CATEGORY = "browser/scripting"
    CASARE_NODE_CLASS = "BrowserRunScriptNode"

    def __init__(self) -> None:
        """Initialize browser script node."""
        super().__init__()
        # Widgets auto-generated by @properties decorator

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("page", DataType.PAGE)
        self.add_typed_input("script", DataType.STRING)
        self.add_exec_output("exec_out")
        self.add_typed_output("page", DataType.PAGE)
        self.add_typed_output("result", DataType.ANY)
