"""
Node Registry Data.

This module contains the mapping of node class names to their module paths.
Used for lazy loading nodes in the nodes package.
"""

from typing import Dict, Union, Tuple

# Registry Key: Node Class Name
# Registry Value: Module path string OR (module path, class name alias)
# Module paths are relative to casare_rpa.nodes package
NODE_REGISTRY: Dict[str, Union[str, Tuple[str, str]]] = {
    # Basic nodes
    "StartNode": "basic_nodes",
    "EndNode": "basic_nodes",
    "CommentNode": "basic_nodes",
    # Browser control nodes
    "LaunchBrowserNode": "browser.lifecycle",
    "CloseBrowserNode": "browser.lifecycle",
    "NewTabNode": "browser.tabs",
    "GetAllImagesNode": "browser.extraction_nodes",
    "DownloadFileNode": "browser.extraction_nodes",
    # Navigation nodes
    "GoToURLNode": "browser.navigation",
    "GoBackNode": "browser.navigation",
    "GoForwardNode": "browser.navigation",
    "RefreshPageNode": "browser.navigation",
    # Interaction nodes
    "ClickElementNode": "browser.interaction",
    "TypeTextNode": "browser.interaction",
    "SelectDropdownNode": "browser.interaction",
    "ImageClickNode": "browser.interaction",
    "PressKeyNode": "browser.interaction",
    # Data extraction nodes
    "ExtractTextNode": "data_nodes",
    "GetAttributeNode": "data_nodes",
    "ScreenshotNode": "data_nodes",
    # Table scraping nodes
    "TableScraperNode": "browser.table_scraper_node",
    # Browser evaluate node
    "BrowserEvaluateNode": "browser.evaluate_node",
    # CAPTCHA nodes
    "DetectCaptchaNode": "browser.captcha",
    "SolveCaptchaNode": "browser.captcha",
    "SolveCaptchaAINode": "browser.captcha_ai",
    # Form nodes
    "FormFieldNode": "browser.form_field_node",
    "FormFillerNode": "browser.form_filler_node",
    "DetectFormsNode": "browser.detect_forms_node",
    # Wait nodes
    "WaitNode": "wait_nodes",
    "WaitForElementNode": "wait_nodes",
    "WaitForNavigationNode": "wait_nodes",
    # Variable nodes
    "SetVariableNode": "variable_nodes",
    "GetVariableNode": "variable_nodes",
    "IncrementVariableNode": "variable_nodes",
    # Control flow nodes - Conditionals
    "IfNode": "control_flow.conditionals",
    "SwitchNode": "control_flow.conditionals",
    "MergeNode": "control_flow.conditionals",
    # Control flow nodes - Loops
    "ForLoopStartNode": "control_flow.loops",
    "ForLoopEndNode": "control_flow.loops",
    "WhileLoopStartNode": "control_flow.loops",
    "WhileLoopEndNode": "control_flow.loops",
    "BreakNode": "control_flow.loops",
    "ContinueNode": "control_flow.loops",
    # Control flow nodes - Error Handling (Try/Catch/Finally)
    "TryNode": "control_flow.error_handling",
    "CatchNode": "control_flow.error_handling",
    "FinallyNode": "control_flow.error_handling",
    # Parallel execution nodes
    "ForkNode": "parallel_nodes",
    "JoinNode": "parallel_nodes",
    "ParallelForEachNode": "parallel_nodes",
    # Error handling nodes
    "RetryNode": "error_handling_nodes",
    "RetrySuccessNode": "error_handling_nodes",
    "RetryFailNode": "error_handling_nodes",
    "ThrowErrorNode": "error_handling_nodes",
    "WebhookNotifyNode": "error_handling_nodes",
    "OnErrorNode": "error_handling_nodes",
    "ErrorRecoveryNode": "error_handling_nodes",
    "LogErrorNode": "error_handling_nodes",
    "AssertNode": "error_handling_nodes",
    # Data operation nodes
    "ConcatenateNode": "string_nodes",
    "FormatStringNode": "string_nodes",
    "RegexMatchNode": "string_nodes",
    "RegexReplaceNode": "string_nodes",
    "MathOperationNode": "math_nodes",
    "ComparisonNode": "math_nodes",
    "CreateListNode": "list_nodes",
    "ListGetItemNode": "list_nodes",
    "JsonParseNode": "dict_nodes",
    "GetPropertyNode": "dict_nodes",
    # List operation nodes
    "ListLengthNode": "list_nodes",
    "ListAppendNode": "list_nodes",
    "ListContainsNode": "list_nodes",
    "ListSliceNode": "list_nodes",
    "ListJoinNode": "list_nodes",
    "ListSortNode": "list_nodes",
    "ListReverseNode": "list_nodes",
    "ListUniqueNode": "list_nodes",
    "ListFilterNode": "list_nodes",
    "ListMapNode": "list_nodes",
    "ListReduceNode": "list_nodes",
    "ListFlattenNode": "list_nodes",
    # Dict operation nodes
    "DictGetNode": "dict_nodes",
    "DictSetNode": "dict_nodes",
    "DictRemoveNode": "dict_nodes",
    "DictMergeNode": "dict_nodes",
    "DictKeysNode": "dict_nodes",
    "DictValuesNode": "dict_nodes",
    "DictHasKeyNode": "dict_nodes",
    "CreateDictNode": "dict_nodes",
    "DictToJsonNode": "dict_nodes",
    "DictItemsNode": "dict_nodes",
    # Data operation nodes (new package)
    "DataCompareNode": "data_operation.compare_node",
    # Utility nodes
    "HttpRequestNode": "http.http_basic",
    "ValidateNode": "utility_nodes",
    "TransformNode": "utility_nodes",
    "LogNode": "utility_nodes",
    # File system nodes - Super Nodes (consolidated)
    "FileSystemSuperNode": "file.super_node",
    "StructuredDataSuperNode": "file.super_node",
    # File system nodes - read operations (legacy)
    "ReadFileNode": "file.file_read_nodes",
    # File system nodes - write operations
    "WriteFileNode": "file.file_write_nodes",
    "AppendFileNode": "file.file_write_nodes",
    # File system nodes - file operations
    "DeleteFileNode": "file.file_system_nodes",
    "CopyFileNode": "file.file_system_nodes",
    "MoveFileNode": "file.file_system_nodes",
    # File system nodes - directory operations
    "CreateDirectoryNode": "file.directory_nodes",
    "ListDirectoryNode": "file.directory_nodes",
    "ListFilesNode": "file.directory_nodes",
    # File system nodes - path info operations
    "FileExistsNode": "file.path_nodes",
    "GetFileSizeNode": "file.path_nodes",
    "GetFileInfoNode": "file.path_nodes",
    # File system nodes - structured data
    "ReadCSVNode": "file.structured_data",
    "WriteCSVNode": "file.structured_data",
    "ReadJSONFileNode": "file.structured_data",
    "WriteJSONFileNode": "file.structured_data",
    "ZipFilesNode": "file.structured_data",
    "UnzipFilesNode": "file.structured_data",
    # File system nodes - image operations
    "ImageConvertNode": "file.image_nodes",
    # Email nodes - send operations
    "SendEmailNode": "email.send_nodes",
    # Email nodes - receive/read operations
    "ReadEmailsNode": "email.receive_nodes",
    "GetEmailContentNode": "email.receive_nodes",
    "FilterEmailsNode": "email.receive_nodes",
    # Email nodes - IMAP management
    "SaveAttachmentNode": "email.imap_nodes",
    "MarkEmailNode": "email.imap_nodes",
    "DeleteEmailNode": "email.imap_nodes",
    "MoveEmailNode": "email.imap_nodes",
    # HTTP/REST API nodes
    # HttpRequestNode is already in utility_nodes but also in http.http_basic. Preferring the specific ones.
    # HTTP/REST API nodes - advanced operations
    "SetHttpHeadersNode": "http.http_advanced",
    "ParseJsonResponseNode": "http.http_advanced",
    "HttpDownloadFileNode": "http.http_advanced",
    "HttpUploadFileNode": "http.http_advanced",
    "BuildUrlNode": "http.http_advanced",
    # HTTP/REST API nodes - authentication
    "HttpAuthNode": "http.http_auth",
    # HTTP/REST API nodes - Super Node (consolidated)
    "HttpSuperNode": "http.http_super_node",
    # Database nodes - SQL operations
    "DatabaseConnectNode": "database.sql_nodes",
    "ExecuteQueryNode": "database.sql_nodes",
    "ExecuteNonQueryNode": "database.sql_nodes",
    "BeginTransactionNode": "database.sql_nodes",
    "CommitTransactionNode": "database.sql_nodes",
    "RollbackTransactionNode": "database.sql_nodes",
    "CloseDatabaseNode": "database.sql_nodes",
    "ExecuteBatchNode": "database.sql_nodes",
    # Database nodes - utilities
    "TableExistsNode": "database.database_utils",
    "GetTableColumnsNode": "database.database_utils",
    # Random nodes
    "RandomNumberNode": "random_nodes",
    "RandomChoiceNode": "random_nodes",
    "RandomStringNode": "random_nodes",
    "RandomUUIDNode": "random_nodes",
    "ShuffleListNode": "random_nodes",
    # DateTime nodes
    "GetCurrentDateTimeNode": "datetime_nodes",
    "FormatDateTimeNode": "datetime_nodes",
    "ParseDateTimeNode": "datetime_nodes",
    "DateTimeAddNode": "datetime_nodes",
    "DateTimeDiffNode": "datetime_nodes",
    "DateTimeCompareNode": "datetime_nodes",
    "GetTimestampNode": "datetime_nodes",
    # Text nodes - Super Nodes (consolidated)
    "TextSuperNode": "text.super_node",
    # Text nodes (Refactored)
    "TextSplitNode": "text.manipulation",
    "TextReplaceNode": "text.manipulation",
    "TextTrimNode": "text.manipulation",
    "TextCaseNode": "text.manipulation",
    "TextPadNode": "text.manipulation",
    "TextReverseNode": "text.manipulation",
    "TextLinesNode": "text.manipulation",
    "TextSubstringNode": "text.search",
    "TextContainsNode": "text.search",
    "TextStartsWithNode": "text.search",
    "TextEndsWithNode": "text.search",
    "TextExtractNode": "text.search",
    "TextCountNode": "text.analysis",
    "TextJoinNode": "text.transform",
    # System nodes - Clipboard operations
    "ClipboardCopyNode": "system.clipboard_nodes",
    "ClipboardPasteNode": "system.clipboard_nodes",
    "ClipboardClearNode": "system.clipboard_nodes",
    # System nodes - Dialog operations (Refactored)
    "MessageBoxNode": "system.dialogs.message",
    "ConfirmDialogNode": "system.dialogs.message",
    "InputDialogNode": "system.dialogs.input",
    "MultilineInputDialogNode": "system.dialogs.input",
    "CredentialDialogNode": "system.dialogs.input",
    "TooltipNode": "system.dialogs.notification",
    "SystemNotificationNode": "system.dialogs.notification",
    "SnackbarNode": "system.dialogs.notification",
    "BalloonTipNode": "system.dialogs.notification",
    "AudioAlertNode": "system.dialogs.notification",
    "ProgressDialogNode": "system.dialogs.progress",
    "SplashScreenNode": "system.dialogs.progress",
    "FilePickerDialogNode": "system.dialogs.picker",
    "FolderPickerDialogNode": "system.dialogs.picker",
    "ColorPickerDialogNode": "system.dialogs.picker",
    "DateTimePickerDialogNode": "system.dialogs.picker",
    "ListPickerDialogNode": "system.dialogs.picker",
    "FormDialogNode": "system.dialogs.form",
    "WizardDialogNode": "system.dialogs.form",
    "ImagePreviewDialogNode": "system.dialogs.preview",
    "TableDialogNode": "system.dialogs.preview",
    # System nodes - Command execution
    "RunCommandNode": "system.command_nodes",
    "RunPowerShellNode": "system.command_nodes",
    # System nodes - Windows Services
    "GetServiceStatusNode": "system.service_nodes",
    "StartServiceNode": "system.service_nodes",
    "StopServiceNode": "system.service_nodes",
    "RestartServiceNode": "system.service_nodes",
    "ListServicesNode": "system.service_nodes",
    # System nodes - System utilities
    "ScreenRegionPickerNode": "system.system_nodes",
    "VolumeControlNode": "system.system_nodes",
    "ProcessListNode": "system.system_nodes",
    "ProcessKillNode": "system.system_nodes",
    "EnvironmentVariableNode": "system.system_nodes",
    "SystemInfoNode": "system.system_nodes",
    # System nodes - Quick nodes
    "HotkeyWaitNode": "system.quick_nodes",
    "BeepNode": "system.quick_nodes",
    "ClipboardMonitorNode": "system.quick_nodes",
    # System nodes - Utility nodes
    "FileWatcherNode": "system.utility_system_nodes",
    "QRCodeNode": "system.utility_system_nodes",
    "Base64Node": "system.utility_system_nodes",
    "UUIDGeneratorNode": "system.utility_system_nodes",
    "AssertSystemNode": "system.utility_system_nodes",
    "LogToFileNode": "system.utility_system_nodes",
    # System nodes - Media nodes
    "TextToSpeechNode": "system.media_nodes",
    "PDFPreviewDialogNode": "system.media_nodes",
    "WebcamCaptureNode": "system.media_nodes",
    # Script nodes
    "RunPythonScriptNode": "script_nodes",
    "RunPythonFileNode": "script_nodes",
    "EvalExpressionNode": "script_nodes",
    "RunBatchScriptNode": "script_nodes",
    "RunJavaScriptNode": "script_nodes",
    # XML nodes
    "ParseXMLNode": "xml_nodes",
    "ReadXMLFileNode": "xml_nodes",
    "WriteXMLFileNode": "xml_nodes",
    "XPathQueryNode": "xml_nodes",
    "GetXMLElementNode": "xml_nodes",
    "GetXMLAttributeNode": "xml_nodes",
    "XMLToJsonNode": "xml_nodes",
    "JsonToXMLNode": "xml_nodes",
    # PDF nodes
    "ReadPDFTextNode": "pdf_nodes",
    "GetPDFInfoNode": "pdf_nodes",
    "MergePDFsNode": "pdf_nodes",
    "SplitPDFNode": "pdf_nodes",
    "ExtractPDFPagesNode": "pdf_nodes",
    "PDFToImagesNode": "pdf_nodes",
    # FTP nodes
    "FTPConnectNode": "ftp_nodes",
    "FTPUploadNode": "ftp_nodes",
    "FTPDownloadNode": "ftp_nodes",
    "FTPListNode": "ftp_nodes",
    "FTPDeleteNode": "ftp_nodes",
    "FTPMakeDirNode": "ftp_nodes",
    "FTPRemoveDirNode": "ftp_nodes",
    "FTPRenameNode": "ftp_nodes",
    "FTPDisconnectNode": "ftp_nodes",
    "FTPGetSizeNode": "ftp_nodes",
    # LLM nodes
    "LLMCompletionNode": "llm.llm_nodes",
    "LLMChatNode": "llm.llm_nodes",
    "LLMExtractDataNode": "llm.llm_nodes",
    "LLMSummarizeNode": "llm.llm_nodes",
    "LLMClassifyNode": "llm.llm_nodes",
    "LLMTranslateNode": "llm.llm_nodes",
    # AI Condition nodes
    "AIConditionNode": "llm.ai_condition_node",
    "AISwitchNode": "llm.ai_switch_node",
    "AIDecisionTableNode": "llm.ai_decision_table_node",
    # AI Agent node
    "AIAgentNode": "llm.ai_agent_node",
    # RAG nodes
    "EmbeddingNode": "llm.rag_nodes",
    "VectorStoreAddNode": "llm.rag_nodes",
    "VectorSearchNode": "llm.rag_nodes",
    "RAGNode": "llm.rag_nodes",
    "VectorStoreDeleteNode": "llm.rag_nodes",
    # Prompt template nodes
    "PromptTemplateNode": "llm.prompt_template_node",
    "ListTemplatesNode": "llm.prompt_template_node",
    "GetTemplateInfoNode": "llm.prompt_template_node",
    # Document AI nodes
    "ClassifyDocumentNode": "document.document_nodes",
    "ExtractInvoiceNode": "document.document_nodes",
    "ExtractFormNode": "document.document_nodes",
    "ExtractTableNode": "document.document_nodes",
    "ValidateExtractionNode": "document.document_nodes",
    # Trigger nodes - General
    "WebhookTriggerNode": "trigger_nodes.webhook_trigger_node",
    "ScheduleTriggerNode": "trigger_nodes.schedule_trigger_node",
    "FileWatchTriggerNode": "trigger_nodes.file_watch_trigger_node",
    "EmailTriggerNode": "trigger_nodes.email_trigger_node",
    "AppEventTriggerNode": "trigger_nodes.app_event_trigger_node",
    "ErrorTriggerNode": "trigger_nodes.error_trigger_node",
    "WorkflowCallTriggerNode": "trigger_nodes.workflow_call_trigger_node",
    "FormTriggerNode": "trigger_nodes.form_trigger_node",
    "ChatTriggerNode": "trigger_nodes.chat_trigger_node",
    "RSSFeedTriggerNode": "trigger_nodes.rss_feed_trigger_node",
    "SSETriggerNode": "trigger_nodes.sse_trigger_node",
    # Trigger nodes - Messaging
    "TelegramTriggerNode": "trigger_nodes.telegram_trigger_node",
    "WhatsAppTriggerNode": "trigger_nodes.whatsapp_trigger_node",
    # Trigger nodes - Google
    "GmailTriggerNode": "trigger_nodes.gmail_trigger_node",
    "DriveTriggerNode": "trigger_nodes.drive_trigger_node",
    "SheetsTriggerNode": "trigger_nodes.sheets_trigger_node",
    # Telegram messaging nodes - Send
    "TelegramSendMessageNode": "messaging.telegram.telegram_send",
    "TelegramSendPhotoNode": "messaging.telegram.telegram_send",
    "TelegramSendDocumentNode": "messaging.telegram.telegram_send",
    "TelegramSendLocationNode": "messaging.telegram.telegram_send",
    # Telegram messaging nodes - Actions
    "TelegramEditMessageNode": "messaging.telegram.telegram_actions",
    "TelegramDeleteMessageNode": "messaging.telegram.telegram_actions",
    "TelegramSendMediaGroupNode": "messaging.telegram.telegram_actions",
    "TelegramAnswerCallbackNode": "messaging.telegram.telegram_actions",
    "TelegramGetUpdatesNode": "messaging.telegram.telegram_actions",
    # WhatsApp messaging nodes
    "WhatsAppSendMessageNode": "messaging.whatsapp.whatsapp_send",
    "WhatsAppSendTemplateNode": "messaging.whatsapp.whatsapp_send",
    "WhatsAppSendImageNode": "messaging.whatsapp.whatsapp_send",
    "WhatsAppSendDocumentNode": "messaging.whatsapp.whatsapp_send",
    "WhatsAppSendVideoNode": "messaging.whatsapp.whatsapp_send",
    "WhatsAppSendLocationNode": "messaging.whatsapp.whatsapp_send",
    "WhatsAppSendInteractiveNode": "messaging.whatsapp.whatsapp_send",
    # Gmail nodes (using new GmailBaseNode with built-in credential handling)
    "GmailSendEmailNode": "google.gmail.gmail_send",
    "GmailSendWithAttachmentNode": "google.gmail.gmail_send",
    "GmailCreateDraftNode": "google.gmail.gmail_send",
    "GmailReplyToEmailNode": "google.gmail.gmail_send",
    "GmailForwardEmailNode": "google.gmail.gmail_send",
    "GmailGetEmailNode": "google.gmail.gmail_read",
    "GmailListEmailsNode": "google.gmail_nodes",
    "GmailSearchEmailsNode": "google.gmail.gmail_read",
    "GmailGetThreadNode": "google.gmail.gmail_read",
    "GmailGetAttachmentNode": "google.gmail.gmail_read",
    "GmailModifyLabelsNode": "google.gmail_nodes",
    "GmailMoveToTrashNode": "google.gmail_nodes",
    "GmailMarkAsReadNode": "google.gmail_nodes",
    "GmailMarkAsUnreadNode": "google.gmail_nodes",
    "GmailStarEmailNode": "google.gmail_nodes",
    "GmailArchiveEmailNode": "google.gmail_nodes",
    "GmailDeleteEmailNode": "google.gmail_nodes",
    "GmailBatchSendNode": "google.gmail_nodes",
    "GmailBatchModifyNode": "google.gmail_nodes",
    "GmailBatchDeleteNode": "google.gmail_nodes",
    # Sheets nodes (from google.sheets_nodes)
    "SheetsGetCellNode": "google.sheets_nodes",
    "SheetsSetCellNode": "google.sheets_nodes",
    "SheetsGetRangeNode": "google.sheets_nodes",
    "SheetsWriteRangeNode": "google.sheets_nodes",
    "SheetsClearRangeNode": "google.sheets_nodes",
    "SheetsCreateSpreadsheetNode": "google.sheets_nodes",
    "SheetsGetSpreadsheetNode": "google.sheets_nodes",
    "SheetsAddSheetNode": "google.sheets_nodes",
    "SheetsDeleteSheetNode": "google.sheets_nodes",
    "SheetsDuplicateSheetNode": "google.sheets_nodes",
    "SheetsRenameSheetNode": "google.sheets_nodes",
    "SheetsAppendRowNode": "google.sheets_nodes",
    "SheetsInsertRowNode": "google.sheets_nodes",
    "SheetsDeleteRowNode": "google.sheets_nodes",
    "SheetsInsertColumnNode": "google.sheets_nodes",
    "SheetsDeleteColumnNode": "google.sheets_nodes",
    "SheetsFormatCellsNode": "google.sheets_nodes",
    "SheetsAutoResizeNode": "google.sheets_nodes",
    "SheetsBatchUpdateNode": "google.sheets_nodes",
    "SheetsBatchGetNode": "google.sheets_nodes",
    "SheetsBatchClearNode": "google.sheets_nodes",
    # Drive nodes (from google.drive_nodes)
    "DriveUploadFileNode": "google.drive_nodes",
    "DriveDownloadFileNode": "google.drive_nodes",
    "DriveDownloadFolderNode": "google.drive_nodes",
    "DriveBatchDownloadNode": "google.drive_nodes",
    "DriveDeleteFileNode": "google.drive_nodes",
    "DriveCopyFileNode": "google.drive_nodes",
    "DriveMoveFileNode": "google.drive_nodes",
    "DriveRenameFileNode": "google.drive_nodes",
    "DriveGetFileNode": "google.drive_nodes",
    "DriveCreateFolderNode": "google.drive_nodes",
    "DriveListFilesNode": "google.drive_nodes",
    "DriveSearchFilesNode": "google.drive_nodes",
    "DriveShareFileNode": "google.drive_nodes",
    "DriveRemovePermissionNode": "google.drive_nodes",
    "DriveGetPermissionsNode": "google.drive_nodes",
    "DriveExportFileNode": "google.drive_nodes",
    "DriveBatchDeleteNode": "google.drive_nodes",
    "DriveBatchMoveNode": "google.drive_nodes",
    "DriveBatchCopyNode": "google.drive_nodes",
    # Desktop/Office automation nodes
    "ExcelOpenNode": "desktop_nodes.office_nodes",
    "ExcelReadCellNode": "desktop_nodes.office_nodes",
    "ExcelWriteCellNode": "desktop_nodes.office_nodes",
    "ExcelGetRangeNode": "desktop_nodes.office_nodes",
    "ExcelCloseNode": "desktop_nodes.office_nodes",
    "WordOpenNode": "desktop_nodes.office_nodes",
    "WordGetTextNode": "desktop_nodes.office_nodes",
    "WordReplaceTextNode": "desktop_nodes.office_nodes",
    "WordCloseNode": "desktop_nodes.office_nodes",
    "OutlookSendEmailNode": "desktop_nodes.office_nodes",
    "OutlookReadEmailsNode": "desktop_nodes.office_nodes",
    "OutlookGetInboxCountNode": "desktop_nodes.office_nodes",
    # Desktop Automation Nodes - Super Nodes (consolidated)
    "WindowManagementSuperNode": "desktop_nodes.window_super_node",
    # Desktop Automation Nodes - Application
    "LaunchApplicationNode": "desktop_nodes",
    "CloseApplicationNode": "desktop_nodes",
    "ActivateWindowNode": "desktop_nodes",
    "GetWindowListNode": "desktop_nodes",
    # Desktop Automation Nodes - Element
    "FindElementNode": "desktop_nodes",
    "DesktopClickElementNode": ("desktop_nodes", "ClickElementNode"),
    "DesktopTypeTextNode": ("desktop_nodes", "TypeTextNode"),
    "GetElementTextNode": "desktop_nodes",
    "GetElementPropertyNode": "desktop_nodes",
    # Desktop Automation Nodes - Window
    "ResizeWindowNode": "desktop_nodes",
    "MoveWindowNode": "desktop_nodes",
    "MaximizeWindowNode": "desktop_nodes",
    "MinimizeWindowNode": "desktop_nodes",
    "RestoreWindowNode": "desktop_nodes",
    "GetWindowPropertiesNode": "desktop_nodes",
    "SetWindowStateNode": "desktop_nodes",
    # Desktop Automation Nodes - Interaction
    "SelectFromDropdownNode": "desktop_nodes",
    "CheckCheckboxNode": "desktop_nodes",
    "SelectRadioButtonNode": "desktop_nodes",
    "SelectTabNode": "desktop_nodes",
    "ExpandTreeItemNode": "desktop_nodes",
    "ScrollElementNode": "desktop_nodes",
    # Desktop Automation Nodes - Mouse/Keyboard
    "MoveMouseNode": "desktop_nodes",
    "MouseClickNode": "desktop_nodes",
    "SendKeysNode": "desktop_nodes",
    "SendHotKeyNode": "desktop_nodes",
    "GetMousePositionNode": "desktop_nodes",
    "DragMouseNode": "desktop_nodes",
    # Desktop Automation Nodes - Wait/Verification
    "DesktopWaitForElementNode": ("desktop_nodes", "WaitForElementNode"),
    "WaitForWindowNode": "desktop_nodes",
    "VerifyElementExistsNode": "desktop_nodes",
    "VerifyElementPropertyNode": "desktop_nodes",
    # Desktop Automation Nodes - Screenshot/OCR
    "CaptureScreenshotNode": "desktop_nodes",
    "CaptureElementImageNode": "desktop_nodes",
    "OCRExtractTextNode": "desktop_nodes",
    "CompareImagesNode": "desktop_nodes",
    # Gmail Label Management Nodes
    "GmailAddLabelNode": "google.gmail_nodes",
    "GmailRemoveLabelNode": "google.gmail_nodes",
    "GmailGetLabelsNode": "google.gmail_nodes",
    "GmailTrashEmailNode": "google.gmail_nodes",
    # Subflow nodes
    "SubflowNode": "subflow_node",
    # Workflow nodes
    "CallSubworkflowNode": "workflow.call_subworkflow_node",
    "ExecuteWorkflowNode": "workflow.execute_workflow_node",
}
