"""
CasareRPA Visual Nodes - Organized by Category

All 142+ visual nodes organized into 12 categories for better navigation.
"""

# Basic (3 nodes)
from .basic import (
    VisualStartNode,
    VisualEndNode,
    VisualCommentNode,
)

# Browser (18 nodes)
from .browser import (
    VisualLaunchBrowserNode,
    VisualCloseBrowserNode,
    VisualNewTabNode,
    VisualGetAllImagesNode,
    VisualDownloadFileNode,
    VisualGoToURLNode,
    VisualGoBackNode,
    VisualGoForwardNode,
    VisualRefreshPageNode,
    VisualClickElementNode,
    VisualTypeTextNode,
    VisualSelectDropdownNode,
    VisualExtractTextNode,
    VisualGetAttributeNode,
    VisualScreenshotNode,
    VisualWaitNode,
    VisualWaitForElementNode,
    VisualWaitForNavigationNode,
)

# Control Flow (10 nodes)
from .control_flow import (
    VisualIfNode,
    VisualForLoopNode,
    VisualForLoopStartNode,
    VisualForLoopEndNode,
    VisualWhileLoopNode,
    VisualWhileLoopStartNode,
    VisualWhileLoopEndNode,
    VisualBreakNode,
    VisualContinueNode,
    VisualSwitchNode,
)

# Database (10 nodes)
from .database import (
    VisualDatabaseConnectNode,
    VisualExecuteQueryNode,
    VisualExecuteNonQueryNode,
    VisualBeginTransactionNode,
    VisualCommitTransactionNode,
    VisualRollbackTransactionNode,
    VisualCloseDatabaseNode,
    VisualTableExistsNode,
    VisualGetTableColumnsNode,
    VisualExecuteBatchNode,
)

# Desktop Automation (36 nodes)
from .desktop_automation import (
    VisualLaunchApplicationNode,
    VisualCloseApplicationNode,
    VisualActivateWindowNode,
    VisualGetWindowListNode,
    VisualFindElementNode,
    VisualClickElementDesktopNode,
    VisualTypeTextDesktopNode,
    VisualGetElementTextNode,
    VisualGetElementPropertyNode,
    VisualResizeWindowNode,
    VisualMoveWindowNode,
    VisualMaximizeWindowNode,
    VisualMinimizeWindowNode,
    VisualRestoreWindowNode,
    VisualGetWindowPropertiesNode,
    VisualSetWindowStateNode,
    VisualSelectFromDropdownNode,
    VisualCheckCheckboxNode,
    VisualSelectRadioButtonNode,
    VisualSelectTabNode,
    VisualExpandTreeItemNode,
    VisualScrollElementNode,
    VisualMoveMouseNode,
    VisualMouseClickNode,
    VisualSendKeysNode,
    VisualSendHotKeyNode,
    VisualGetMousePositionNode,
    VisualDragMouseNode,
    VisualDesktopWaitForElementNode,
    VisualWaitForWindowNode,
    VisualVerifyElementExistsNode,
    VisualVerifyElementPropertyNode,
    VisualCaptureScreenshotNode,
    VisualCaptureElementImageNode,
    VisualOCRExtractTextNode,
    VisualCompareImagesNode,
)

# Email (8 nodes)
from .email import (
    VisualSendEmailNode,
    VisualReadEmailsNode,
    VisualGetEmailContentNode,
    VisualSaveAttachmentNode,
    VisualFilterEmailsNode,
    VisualMarkEmailNode,
    VisualDeleteEmailNode,
    VisualMoveEmailNode,
)

# Error Handling (10 nodes)
from .error_handling import (
    VisualTryNode,
    VisualRetryNode,
    VisualRetrySuccessNode,
    VisualRetryFailNode,
    VisualThrowErrorNode,
    VisualWebhookNotifyNode,
    VisualOnErrorNode,
    VisualErrorRecoveryNode,
    VisualLogErrorNode,
    VisualAssertNode,
)

# File Operations (16 nodes)
from .file_operations import (
    VisualReadFileNode,
    VisualWriteFileNode,
    VisualAppendFileNode,
    VisualDeleteFileNode,
    VisualCopyFileNode,
    VisualMoveFileNode,
    VisualCreateDirectoryNode,
    VisualListDirectoryNode,
    VisualFileExistsNode,
    VisualGetFileInfoNode,
    VisualReadCSVNode,
    VisualWriteCSVNode,
    VisualReadJSONFileNode,
    VisualWriteJSONFileNode,
    VisualZipFilesNode,
    VisualUnzipFilesNode,
)

# Office Automation (12 nodes)
from .office_automation import (
    VisualExcelOpenNode,
    VisualExcelReadCellNode,
    VisualExcelWriteCellNode,
    VisualExcelGetRangeNode,
    VisualExcelCloseNode,
    VisualWordOpenNode,
    VisualWordGetTextNode,
    VisualWordReplaceTextNode,
    VisualWordCloseNode,
    VisualOutlookSendEmailNode,
    VisualOutlookReadEmailsNode,
    VisualOutlookGetInboxCountNode,
)

# Rest Api (12 nodes)
from .rest_api import (
    VisualHttpRequestNode,
    VisualHttpGetNode,
    VisualHttpPostNode,
    VisualHttpPutNode,
    VisualHttpPatchNode,
    VisualHttpDeleteNode,
    VisualSetHttpHeadersNode,
    VisualHttpAuthNode,
    VisualParseJsonResponseNode,
    VisualHttpDownloadFileNode,
    VisualHttpUploadFileNode,
    VisualBuildUrlNode,
)

# Utility (4 nodes)
from .utility import (
    VisualHttpRequestNode,
    VisualValidateNode,
    VisualTransformNode,
    VisualLogNode,
)

# Variable (3 nodes)
from .variable import (
    VisualSetVariableNode,
    VisualGetVariableNode,
    VisualIncrementVariableNode,
)

__all__ = [
    # basic
    "VisualStartNode",
    "VisualEndNode",
    "VisualCommentNode",
    # browser
    "VisualLaunchBrowserNode",
    "VisualCloseBrowserNode",
    "VisualNewTabNode",
    "VisualGetAllImagesNode",
    "VisualDownloadFileNode",
    "VisualGoToURLNode",
    "VisualGoBackNode",
    "VisualGoForwardNode",
    "VisualRefreshPageNode",
    "VisualClickElementNode",
    "VisualTypeTextNode",
    "VisualSelectDropdownNode",
    "VisualExtractTextNode",
    "VisualGetAttributeNode",
    "VisualScreenshotNode",
    "VisualWaitNode",
    "VisualWaitForElementNode",
    "VisualWaitForNavigationNode",
    # control_flow
    "VisualIfNode",
    "VisualForLoopNode",
    "VisualForLoopStartNode",
    "VisualForLoopEndNode",
    "VisualWhileLoopNode",
    "VisualWhileLoopStartNode",
    "VisualWhileLoopEndNode",
    "VisualBreakNode",
    "VisualContinueNode",
    "VisualSwitchNode",
    # database
    "VisualDatabaseConnectNode",
    "VisualExecuteQueryNode",
    "VisualExecuteNonQueryNode",
    "VisualBeginTransactionNode",
    "VisualCommitTransactionNode",
    "VisualRollbackTransactionNode",
    "VisualCloseDatabaseNode",
    "VisualTableExistsNode",
    "VisualGetTableColumnsNode",
    "VisualExecuteBatchNode",
    # desktop_automation
    "VisualLaunchApplicationNode",
    "VisualCloseApplicationNode",
    "VisualActivateWindowNode",
    "VisualGetWindowListNode",
    "VisualFindElementNode",
    "VisualClickElementDesktopNode",
    "VisualTypeTextDesktopNode",
    "VisualGetElementTextNode",
    "VisualGetElementPropertyNode",
    "VisualResizeWindowNode",
    "VisualMoveWindowNode",
    "VisualMaximizeWindowNode",
    "VisualMinimizeWindowNode",
    "VisualRestoreWindowNode",
    "VisualGetWindowPropertiesNode",
    "VisualSetWindowStateNode",
    "VisualSelectFromDropdownNode",
    "VisualCheckCheckboxNode",
    "VisualSelectRadioButtonNode",
    "VisualSelectTabNode",
    "VisualExpandTreeItemNode",
    "VisualScrollElementNode",
    "VisualMoveMouseNode",
    "VisualMouseClickNode",
    "VisualSendKeysNode",
    "VisualSendHotKeyNode",
    "VisualGetMousePositionNode",
    "VisualDragMouseNode",
    "VisualDesktopWaitForElementNode",
    "VisualWaitForWindowNode",
    "VisualVerifyElementExistsNode",
    "VisualVerifyElementPropertyNode",
    "VisualCaptureScreenshotNode",
    "VisualCaptureElementImageNode",
    "VisualOCRExtractTextNode",
    "VisualCompareImagesNode",
    # email
    "VisualSendEmailNode",
    "VisualReadEmailsNode",
    "VisualGetEmailContentNode",
    "VisualSaveAttachmentNode",
    "VisualFilterEmailsNode",
    "VisualMarkEmailNode",
    "VisualDeleteEmailNode",
    "VisualMoveEmailNode",
    # error_handling
    "VisualTryNode",
    "VisualRetryNode",
    "VisualRetrySuccessNode",
    "VisualRetryFailNode",
    "VisualThrowErrorNode",
    "VisualWebhookNotifyNode",
    "VisualOnErrorNode",
    "VisualErrorRecoveryNode",
    "VisualLogErrorNode",
    "VisualAssertNode",
    # file_operations
    "VisualReadFileNode",
    "VisualWriteFileNode",
    "VisualAppendFileNode",
    "VisualDeleteFileNode",
    "VisualCopyFileNode",
    "VisualMoveFileNode",
    "VisualCreateDirectoryNode",
    "VisualListDirectoryNode",
    "VisualFileExistsNode",
    "VisualGetFileInfoNode",
    "VisualReadCSVNode",
    "VisualWriteCSVNode",
    "VisualReadJSONFileNode",
    "VisualWriteJSONFileNode",
    "VisualZipFilesNode",
    "VisualUnzipFilesNode",
    # office_automation
    "VisualExcelOpenNode",
    "VisualExcelReadCellNode",
    "VisualExcelWriteCellNode",
    "VisualExcelGetRangeNode",
    "VisualExcelCloseNode",
    "VisualWordOpenNode",
    "VisualWordGetTextNode",
    "VisualWordReplaceTextNode",
    "VisualWordCloseNode",
    "VisualOutlookSendEmailNode",
    "VisualOutlookReadEmailsNode",
    "VisualOutlookGetInboxCountNode",
    # rest_api
    "VisualHttpRequestNode",
    "VisualHttpGetNode",
    "VisualHttpPostNode",
    "VisualHttpPutNode",
    "VisualHttpPatchNode",
    "VisualHttpDeleteNode",
    "VisualSetHttpHeadersNode",
    "VisualHttpAuthNode",
    "VisualParseJsonResponseNode",
    "VisualHttpDownloadFileNode",
    "VisualHttpUploadFileNode",
    "VisualBuildUrlNode",
    # utility
    "VisualHttpRequestNode",
    "VisualValidateNode",
    "VisualTransformNode",
    "VisualLogNode",
    # variable
    "VisualSetVariableNode",
    "VisualGetVariableNode",
    "VisualIncrementVariableNode",
]
