"""
CasareRPA Visual Nodes - Organized by Category

All visual nodes organized into categories for better navigation.
"""

# Basic (3 nodes)
from .basic import (
    VisualStartNode,
    VisualEndNode,
    VisualCommentNode,
)

# Browser (18 nodes)
from .browser import (
    VisualLaunchBrowserNode,
    VisualCloseBrowserNode,
    VisualNewTabNode,
    VisualGetAllImagesNode,
    VisualDownloadFileNode,
    VisualGoToURLNode,
    VisualGoBackNode,
    VisualGoForwardNode,
    VisualRefreshPageNode,
    VisualClickElementNode,
    VisualTypeTextNode,
    VisualSelectDropdownNode,
    VisualExtractTextNode,
    VisualGetAttributeNode,
    VisualScreenshotNode,
    VisualWaitNode,
    VisualWaitForElementNode,
    VisualWaitForNavigationNode,
)

# Control Flow (10 nodes)
from .control_flow import (
    VisualIfNode,
    VisualForLoopNode,
    VisualForLoopStartNode,
    VisualForLoopEndNode,
    VisualWhileLoopNode,
    VisualWhileLoopStartNode,
    VisualWhileLoopEndNode,
    VisualBreakNode,
    VisualContinueNode,
    VisualSwitchNode,
)

# Database (10 nodes)
from .database import (
    VisualDatabaseConnectNode,
    VisualExecuteQueryNode,
    VisualExecuteNonQueryNode,
    VisualBeginTransactionNode,
    VisualCommitTransactionNode,
    VisualRollbackTransactionNode,
    VisualCloseDatabaseNode,
    VisualTableExistsNode,
    VisualGetTableColumnsNode,
    VisualExecuteBatchNode,
)

# Data Operations (40 nodes) - NEW
from .data_operations import (
    # Data operations
    VisualConcatenateNode,
    VisualFormatStringNode,
    VisualRegexMatchNode,
    VisualRegexReplaceNode,
    VisualMathOperationNode,
    VisualComparisonNode,
    VisualCreateListNode,
    VisualListGetItemNode,
    VisualJsonParseNode,
    VisualGetPropertyNode,
    # List operations
    VisualListLengthNode,
    VisualListAppendNode,
    VisualListContainsNode,
    VisualListSliceNode,
    VisualListJoinNode,
    VisualListSortNode,
    VisualListReverseNode,
    VisualListUniqueNode,
    VisualListFilterNode,
    VisualListMapNode,
    VisualListReduceNode,
    VisualListFlattenNode,
    # Dict operations
    VisualDictGetNode,
    VisualDictSetNode,
    VisualDictRemoveNode,
    VisualDictMergeNode,
    VisualDictKeysNode,
    VisualDictValuesNode,
    VisualDictHasKeyNode,
    VisualCreateDictNode,
    VisualDictToJsonNode,
    VisualDictItemsNode,
)

# Desktop Automation (36 nodes)
from .desktop_automation import (
    VisualLaunchApplicationNode,
    VisualCloseApplicationNode,
    VisualActivateWindowNode,
    VisualGetWindowListNode,
    VisualFindElementNode,
    VisualClickElementDesktopNode,
    VisualTypeTextDesktopNode,
    VisualGetElementTextNode,
    VisualGetElementPropertyNode,
    VisualResizeWindowNode,
    VisualMoveWindowNode,
    VisualMaximizeWindowNode,
    VisualMinimizeWindowNode,
    VisualRestoreWindowNode,
    VisualGetWindowPropertiesNode,
    VisualSetWindowStateNode,
    VisualSelectFromDropdownNode,
    VisualCheckCheckboxNode,
    VisualSelectRadioButtonNode,
    VisualSelectTabNode,
    VisualExpandTreeItemNode,
    VisualScrollElementNode,
    VisualMoveMouseNode,
    VisualMouseClickNode,
    VisualSendKeysNode,
    VisualSendHotKeyNode,
    VisualGetMousePositionNode,
    VisualDragMouseNode,
    VisualDesktopWaitForElementNode,
    VisualWaitForWindowNode,
    VisualVerifyElementExistsNode,
    VisualVerifyElementPropertyNode,
    VisualCaptureScreenshotNode,
    VisualCaptureElementImageNode,
    VisualOCRExtractTextNode,
    VisualCompareImagesNode,
)

# Email (8 nodes)
from .email import (
    VisualSendEmailNode,
    VisualReadEmailsNode,
    VisualGetEmailContentNode,
    VisualSaveAttachmentNode,
    VisualFilterEmailsNode,
    VisualMarkEmailNode,
    VisualDeleteEmailNode,
    VisualMoveEmailNode,
)

# Error Handling (10 nodes)
from .error_handling import (
    VisualTryNode,
    VisualRetryNode,
    VisualRetrySuccessNode,
    VisualRetryFailNode,
    VisualThrowErrorNode,
    VisualWebhookNotifyNode,
    VisualOnErrorNode,
    VisualErrorRecoveryNode,
    VisualLogErrorNode,
    VisualAssertNode,
)

# File Operations (40 nodes)
from .file_operations import (
    VisualReadFileNode,
    VisualWriteFileNode,
    VisualAppendFileNode,
    VisualDeleteFileNode,
    VisualCopyFileNode,
    VisualMoveFileNode,
    VisualFileExistsNode,
    VisualGetFileSizeNode,
    VisualGetFileInfoNode,
    VisualListFilesNode,
    VisualReadCsvNode,
    VisualWriteCsvNode,
    VisualReadJsonNode,
    VisualWriteJsonNode,
    VisualZipFilesNode,
    VisualUnzipFileNode,
    VisualParseXMLNode,
    VisualReadXMLFileNode,
    VisualWriteXMLFileNode,
    VisualXPathQueryNode,
    VisualGetXMLElementNode,
    VisualGetXMLAttributeNode,
    VisualXMLToJsonNode,
    VisualJsonToXMLNode,
    VisualReadPDFTextNode,
    VisualGetPDFInfoNode,
    VisualMergePDFsNode,
    VisualSplitPDFNode,
    VisualExtractPDFPagesNode,
    VisualPDFToImagesNode,
    VisualFTPConnectNode,
    VisualFTPUploadNode,
    VisualFTPDownloadNode,
    VisualFTPListNode,
    VisualFTPDeleteNode,
    VisualFTPMakeDirNode,
    VisualFTPRemoveDirNode,
    VisualFTPRenameNode,
    VisualFTPDisconnectNode,
    VisualFTPGetSizeNode,
)

# Scripts (5 nodes)
from .scripts import (
    VisualRunPythonScriptNode,
    VisualRunPythonFileNode,
    VisualEvalExpressionNode,
    VisualRunBatchScriptNode,
    VisualRunJavaScriptNode,
)

# System (13 nodes)
from .system import (
    # Clipboard operations
    VisualClipboardCopyNode,
    VisualClipboardPasteNode,
    VisualClipboardClearNode,
    # Dialogs
    VisualMessageBoxNode,
    VisualInputDialogNode,
    VisualTooltipNode,
    # Terminal
    VisualRunCommandNode,
    VisualRunPowerShellNode,
    # Windows Services
    VisualGetServiceStatusNode,
    VisualStartServiceNode,
    VisualStopServiceNode,
    VisualRestartServiceNode,
    VisualListServicesNode,
)

# Utility (26 nodes)
from .utility import (
    VisualRandomNumberNode,
    VisualRandomChoiceNode,
    VisualRandomStringNode,
    VisualRandomUUIDNode,
    VisualShuffleListNode,
    VisualGetCurrentDateTimeNode,
    VisualFormatDateTimeNode,
    VisualParseDateTimeNode,
    VisualDateTimeAddNode,
    VisualDateTimeDiffNode,
    VisualDateTimeCompareNode,
    VisualGetTimestampNode,
    VisualTextSplitNode,
    VisualTextReplaceNode,
    VisualTextTrimNode,
    VisualTextCaseNode,
    VisualTextPadNode,
    VisualTextSubstringNode,
    VisualTextContainsNode,
    VisualTextStartsWithNode,
    VisualTextEndsWithNode,
    VisualTextLinesNode,
    VisualTextReverseNode,
    VisualTextCountNode,
    VisualTextJoinNode,
    VisualTextExtractNode,
)

# Office Automation (12 nodes)
from .office_automation import (
    VisualExcelOpenNode,
    VisualExcelReadCellNode,
    VisualExcelWriteCellNode,
    VisualExcelGetRangeNode,
    VisualExcelCloseNode,
    VisualWordOpenNode,
    VisualWordGetTextNode,
    VisualWordReplaceTextNode,
    VisualWordCloseNode,
    VisualOutlookSendEmailNode,
    VisualOutlookReadEmailsNode,
    VisualOutlookGetInboxCountNode,
)

# REST API (12 nodes)
from .rest_api import (
    VisualHttpRequestNode,
    VisualHttpGetNode,
    VisualHttpPostNode,
    VisualHttpPutNode,
    VisualHttpPatchNode,
    VisualHttpDeleteNode,
    VisualSetHttpHeadersNode,
    VisualHttpAuthNode,
    VisualParseJsonResponseNode,
    VisualHttpDownloadFileNode,
    VisualHttpUploadFileNode,
    VisualBuildUrlNode,
)

# Variable (3 nodes)
from .variable import (
    VisualSetVariableNode,
    VisualGetVariableNode,
    VisualIncrementVariableNode,
)

__all__ = [
    # basic
    "VisualStartNode",
    "VisualEndNode",
    "VisualCommentNode",
    # browser
    "VisualLaunchBrowserNode",
    "VisualCloseBrowserNode",
    "VisualNewTabNode",
    "VisualGetAllImagesNode",
    "VisualDownloadFileNode",
    "VisualGoToURLNode",
    "VisualGoBackNode",
    "VisualGoForwardNode",
    "VisualRefreshPageNode",
    "VisualClickElementNode",
    "VisualTypeTextNode",
    "VisualSelectDropdownNode",
    "VisualExtractTextNode",
    "VisualGetAttributeNode",
    "VisualScreenshotNode",
    "VisualWaitNode",
    "VisualWaitForElementNode",
    "VisualWaitForNavigationNode",
    # control_flow
    "VisualIfNode",
    "VisualForLoopNode",
    "VisualForLoopStartNode",
    "VisualForLoopEndNode",
    "VisualWhileLoopNode",
    "VisualWhileLoopStartNode",
    "VisualWhileLoopEndNode",
    "VisualBreakNode",
    "VisualContinueNode",
    "VisualSwitchNode",
    # database
    "VisualDatabaseConnectNode",
    "VisualExecuteQueryNode",
    "VisualExecuteNonQueryNode",
    "VisualBeginTransactionNode",
    "VisualCommitTransactionNode",
    "VisualRollbackTransactionNode",
    "VisualCloseDatabaseNode",
    "VisualTableExistsNode",
    "VisualGetTableColumnsNode",
    "VisualExecuteBatchNode",
    # data_operations
    "VisualConcatenateNode",
    "VisualFormatStringNode",
    "VisualRegexMatchNode",
    "VisualRegexReplaceNode",
    "VisualMathOperationNode",
    "VisualComparisonNode",
    "VisualCreateListNode",
    "VisualListGetItemNode",
    "VisualJsonParseNode",
    "VisualGetPropertyNode",
    "VisualListLengthNode",
    "VisualListAppendNode",
    "VisualListContainsNode",
    "VisualListSliceNode",
    "VisualListJoinNode",
    "VisualListSortNode",
    "VisualListReverseNode",
    "VisualListUniqueNode",
    "VisualListFilterNode",
    "VisualListMapNode",
    "VisualListReduceNode",
    "VisualListFlattenNode",
    "VisualDictGetNode",
    "VisualDictSetNode",
    "VisualDictRemoveNode",
    "VisualDictMergeNode",
    "VisualDictKeysNode",
    "VisualDictValuesNode",
    "VisualDictHasKeyNode",
    "VisualCreateDictNode",
    "VisualDictToJsonNode",
    "VisualDictItemsNode",
    # desktop_automation
    "VisualLaunchApplicationNode",
    "VisualCloseApplicationNode",
    "VisualActivateWindowNode",
    "VisualGetWindowListNode",
    "VisualFindElementNode",
    "VisualClickElementDesktopNode",
    "VisualTypeTextDesktopNode",
    "VisualGetElementTextNode",
    "VisualGetElementPropertyNode",
    "VisualResizeWindowNode",
    "VisualMoveWindowNode",
    "VisualMaximizeWindowNode",
    "VisualMinimizeWindowNode",
    "VisualRestoreWindowNode",
    "VisualGetWindowPropertiesNode",
    "VisualSetWindowStateNode",
    "VisualSelectFromDropdownNode",
    "VisualCheckCheckboxNode",
    "VisualSelectRadioButtonNode",
    "VisualSelectTabNode",
    "VisualExpandTreeItemNode",
    "VisualScrollElementNode",
    "VisualMoveMouseNode",
    "VisualMouseClickNode",
    "VisualSendKeysNode",
    "VisualSendHotKeyNode",
    "VisualGetMousePositionNode",
    "VisualDragMouseNode",
    "VisualDesktopWaitForElementNode",
    "VisualWaitForWindowNode",
    "VisualVerifyElementExistsNode",
    "VisualVerifyElementPropertyNode",
    "VisualCaptureScreenshotNode",
    "VisualCaptureElementImageNode",
    "VisualOCRExtractTextNode",
    "VisualCompareImagesNode",
    # email
    "VisualSendEmailNode",
    "VisualReadEmailsNode",
    "VisualGetEmailContentNode",
    "VisualSaveAttachmentNode",
    "VisualFilterEmailsNode",
    "VisualMarkEmailNode",
    "VisualDeleteEmailNode",
    "VisualMoveEmailNode",
    # error_handling
    "VisualTryNode",
    "VisualRetryNode",
    "VisualRetrySuccessNode",
    "VisualRetryFailNode",
    "VisualThrowErrorNode",
    "VisualWebhookNotifyNode",
    "VisualOnErrorNode",
    "VisualErrorRecoveryNode",
    "VisualLogErrorNode",
    "VisualAssertNode",
    # file_operations
    "VisualReadFileNode",
    "VisualWriteFileNode",
    "VisualAppendFileNode",
    "VisualDeleteFileNode",
    "VisualCopyFileNode",
    "VisualMoveFileNode",
    "VisualFileExistsNode",
    "VisualGetFileSizeNode",
    "VisualGetFileInfoNode",
    "VisualListFilesNode",
    "VisualReadCsvNode",
    "VisualWriteCsvNode",
    "VisualReadJsonNode",
    "VisualWriteJsonNode",
    "VisualZipFilesNode",
    "VisualUnzipFileNode",
    "VisualParseXMLNode",
    "VisualReadXMLFileNode",
    "VisualWriteXMLFileNode",
    "VisualXPathQueryNode",
    "VisualGetXMLElementNode",
    "VisualGetXMLAttributeNode",
    "VisualXMLToJsonNode",
    "VisualJsonToXMLNode",
    "VisualReadPDFTextNode",
    "VisualGetPDFInfoNode",
    "VisualMergePDFsNode",
    "VisualSplitPDFNode",
    "VisualExtractPDFPagesNode",
    "VisualPDFToImagesNode",
    "VisualFTPConnectNode",
    "VisualFTPUploadNode",
    "VisualFTPDownloadNode",
    "VisualFTPListNode",
    "VisualFTPDeleteNode",
    "VisualFTPMakeDirNode",
    "VisualFTPRemoveDirNode",
    "VisualFTPRenameNode",
    "VisualFTPDisconnectNode",
    "VisualFTPGetSizeNode",
    # scripts
    "VisualRunPythonScriptNode",
    "VisualRunPythonFileNode",
    "VisualEvalExpressionNode",
    "VisualRunBatchScriptNode",
    "VisualRunJavaScriptNode",
    # system
    "VisualClipboardCopyNode",
    "VisualClipboardPasteNode",
    "VisualClipboardClearNode",
    "VisualMessageBoxNode",
    "VisualInputDialogNode",
    "VisualTooltipNode",
    "VisualRunCommandNode",
    "VisualRunPowerShellNode",
    "VisualGetServiceStatusNode",
    "VisualStartServiceNode",
    "VisualStopServiceNode",
    "VisualRestartServiceNode",
    "VisualListServicesNode",
    # utility
    "VisualRandomNumberNode",
    "VisualRandomChoiceNode",
    "VisualRandomStringNode",
    "VisualRandomUUIDNode",
    "VisualShuffleListNode",
    "VisualGetCurrentDateTimeNode",
    "VisualFormatDateTimeNode",
    "VisualParseDateTimeNode",
    "VisualDateTimeAddNode",
    "VisualDateTimeDiffNode",
    "VisualDateTimeCompareNode",
    "VisualGetTimestampNode",
    "VisualTextSplitNode",
    "VisualTextReplaceNode",
    "VisualTextTrimNode",
    "VisualTextCaseNode",
    "VisualTextPadNode",
    "VisualTextSubstringNode",
    "VisualTextContainsNode",
    "VisualTextStartsWithNode",
    "VisualTextEndsWithNode",
    "VisualTextLinesNode",
    "VisualTextReverseNode",
    "VisualTextCountNode",
    "VisualTextJoinNode",
    "VisualTextExtractNode",
    # office_automation
    "VisualExcelOpenNode",
    "VisualExcelReadCellNode",
    "VisualExcelWriteCellNode",
    "VisualExcelGetRangeNode",
    "VisualExcelCloseNode",
    "VisualWordOpenNode",
    "VisualWordGetTextNode",
    "VisualWordReplaceTextNode",
    "VisualWordCloseNode",
    "VisualOutlookSendEmailNode",
    "VisualOutlookReadEmailsNode",
    "VisualOutlookGetInboxCountNode",
    # rest_api
    "VisualHttpRequestNode",
    "VisualHttpGetNode",
    "VisualHttpPostNode",
    "VisualHttpPutNode",
    "VisualHttpPatchNode",
    "VisualHttpDeleteNode",
    "VisualSetHttpHeadersNode",
    "VisualHttpAuthNode",
    "VisualParseJsonResponseNode",
    "VisualHttpDownloadFileNode",
    "VisualHttpUploadFileNode",
    "VisualBuildUrlNode",
    # variable
    "VisualSetVariableNode",
    "VisualGetVariableNode",
    "VisualIncrementVariableNode",
]

# =============================================================================
# ALL_VISUAL_NODE_CLASSES - For node registration
# =============================================================================

# Collect all classes from this module's __all__ list
_THIS_MODULE_CLASSES = [globals()[name] for name in __all__]

# Import extended nodes from old location (until migration is complete)
try:
    from casare_rpa.canvas.visual_nodes.extended_visual_nodes import (
        EXTENDED_VISUAL_NODE_CLASSES,
    )

    _EXTENDED_CLASSES = EXTENDED_VISUAL_NODE_CLASSES
except ImportError:
    _EXTENDED_CLASSES = []

# Combine all classes: this module + extended
# Note: data_operations nodes are now in _THIS_MODULE_CLASSES
ALL_VISUAL_NODE_CLASSES = _THIS_MODULE_CLASSES + _EXTENDED_CLASSES
