"""Visual nodes for office_automation category.

Widget Auto-Generation:
-----------------------
Excel nodes use @node_schema decorator on domain nodes for automatic widget generation.
Modern widgets with {x} variable picker button are auto-generated from PropertyDef.
"""

from casare_rpa.domain.value_objects.types import DataType
from casare_rpa.presentation.canvas.visual_nodes.base_visual_node import VisualNode


class VisualExcelOpenNode(VisualNode):
    """Visual representation of ExcelOpenNode."""

    __identifier__ = "casare_rpa.office"
    NODE_NAME = "Excel Open"
    NODE_CATEGORY = "office_automation/excel"
    CASARE_NODE_MODULE = "office"

    def __init__(self) -> None:
        """Initialize Excel Open node."""
        super().__init__()
        # Widgets auto-generated by @node_schema decorator

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("file_path", DataType.STRING)
        self.add_exec_output("exec_out")
        self.add_typed_output("workbook", DataType.WORKBOOK)
        self.add_typed_output("success", DataType.BOOLEAN)


class VisualExcelReadCellNode(VisualNode):
    """Visual representation of ExcelReadCellNode."""

    __identifier__ = "casare_rpa.office"
    NODE_NAME = "Excel Read Cell"
    NODE_CATEGORY = "office_automation/excel"
    CASARE_NODE_MODULE = "office"

    def __init__(self) -> None:
        """Initialize Excel Read Cell node."""
        super().__init__()
        # Widgets auto-generated by @node_schema decorator

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("workbook", DataType.WORKBOOK)
        self.add_typed_input("cell", DataType.STRING)
        self.add_typed_input("sheet", DataType.STRING)
        self.add_exec_output("exec_out")
        self.add_typed_output("value", DataType.ANY)
        self.add_typed_output("success", DataType.BOOLEAN)


class VisualExcelWriteCellNode(VisualNode):
    """Visual representation of ExcelWriteCellNode."""

    __identifier__ = "casare_rpa.office"
    NODE_NAME = "Excel Write Cell"
    NODE_CATEGORY = "office_automation/excel"
    CASARE_NODE_MODULE = "office"

    def __init__(self) -> None:
        """Initialize Excel Write Cell node."""
        super().__init__()
        # Widgets auto-generated by @node_schema decorator

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("workbook", DataType.WORKBOOK)
        self.add_typed_input("cell", DataType.STRING)
        self.add_typed_input("value", DataType.ANY)
        self.add_typed_input("sheet", DataType.STRING)
        self.add_exec_output("exec_out")
        self.add_typed_output("success", DataType.BOOLEAN)


class VisualExcelGetRangeNode(VisualNode):
    """Visual representation of ExcelGetRangeNode."""

    __identifier__ = "casare_rpa.office"
    NODE_NAME = "Excel Get Range"
    NODE_CATEGORY = "office_automation/excel"
    CASARE_NODE_MODULE = "office"

    def __init__(self) -> None:
        """Initialize Excel Get Range node."""
        super().__init__()
        # Widgets auto-generated by @node_schema decorator

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("workbook", DataType.WORKBOOK)
        self.add_typed_input("range", DataType.STRING)
        self.add_typed_input("sheet", DataType.STRING)
        self.add_exec_output("exec_out")
        self.add_typed_output("data", DataType.LIST)
        self.add_typed_output("rows", DataType.INTEGER)
        self.add_typed_output("columns", DataType.INTEGER)
        self.add_typed_output("success", DataType.BOOLEAN)


class VisualExcelCloseNode(VisualNode):
    """Visual representation of ExcelCloseNode."""

    __identifier__ = "casare_rpa.office"
    NODE_NAME = "Excel Close"
    NODE_CATEGORY = "office_automation/excel"
    CASARE_NODE_MODULE = "office"

    def __init__(self) -> None:
        """Initialize Excel Close node."""
        super().__init__()
        # Widgets auto-generated by @node_schema decorator

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("workbook", DataType.WORKBOOK)
        self.add_exec_output("exec_out")
        self.add_typed_output("success", DataType.BOOLEAN)


class VisualWordOpenNode(VisualNode):
    """Visual representation of WordOpenNode."""

    __identifier__ = "casare_rpa.office"
    NODE_NAME = "Word Open"
    NODE_CATEGORY = "office_automation/word"
    CASARE_NODE_MODULE = "office"

    def __init__(self) -> None:
        """Initialize Word Open node."""
        super().__init__()
        # Widgets auto-generated by @node_schema decorator

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("file_path", DataType.STRING)
        self.add_exec_output("exec_out")
        self.add_typed_output("document", DataType.DOCUMENT)
        self.add_typed_output("success", DataType.BOOLEAN)


class VisualWordGetTextNode(VisualNode):
    """Visual representation of WordGetTextNode."""

    __identifier__ = "casare_rpa.office"
    NODE_NAME = "Word Get Text"
    NODE_CATEGORY = "office_automation/word"
    CASARE_NODE_MODULE = "office"

    def __init__(self) -> None:
        """Initialize Word Get Text node."""
        super().__init__()
        # No config properties - input port driven

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("document", DataType.DOCUMENT)
        self.add_exec_output("exec_out")
        self.add_typed_output("text", DataType.STRING)
        self.add_typed_output("word_count", DataType.INTEGER)
        self.add_typed_output("success", DataType.BOOLEAN)


class VisualWordReplaceTextNode(VisualNode):
    """Visual representation of WordReplaceTextNode."""

    __identifier__ = "casare_rpa.office"
    NODE_NAME = "Word Replace Text"
    NODE_CATEGORY = "office_automation/word"
    CASARE_NODE_MODULE = "office"

    def __init__(self) -> None:
        """Initialize Word Replace Text node."""
        super().__init__()
        # Widgets auto-generated by @node_schema decorator

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("document", DataType.DOCUMENT)
        self.add_typed_input("find_text", DataType.STRING)
        self.add_typed_input("replace_text", DataType.STRING)
        self.add_exec_output("exec_out")
        self.add_typed_output("replacements", DataType.INTEGER)
        self.add_typed_output("success", DataType.BOOLEAN)


class VisualWordCloseNode(VisualNode):
    """Visual representation of WordCloseNode."""

    __identifier__ = "casare_rpa.office"
    NODE_NAME = "Word Close"
    NODE_CATEGORY = "office_automation/word"
    CASARE_NODE_MODULE = "office"

    def __init__(self) -> None:
        """Initialize Word Close node."""
        super().__init__()
        # Widgets auto-generated by @node_schema decorator

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("document", DataType.DOCUMENT)
        self.add_exec_output("exec_out")
        self.add_typed_output("success", DataType.BOOLEAN)


class VisualOutlookSendEmailNode(VisualNode):
    """Visual representation of OutlookSendEmailNode."""

    __identifier__ = "casare_rpa.office"
    NODE_NAME = "Outlook Send Email"
    NODE_CATEGORY = "office_automation/outlook"
    CASARE_NODE_MODULE = "office"

    def __init__(self) -> None:
        """Initialize Outlook Send Email node."""
        super().__init__()
        # Widgets auto-generated by @node_schema decorator

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_typed_input("to", DataType.STRING)
        self.add_typed_input("subject", DataType.STRING)
        self.add_typed_input("body", DataType.STRING)
        self.add_typed_input("attachments", DataType.LIST)
        self.add_exec_output("exec_out")
        self.add_typed_output("success", DataType.BOOLEAN)


class VisualOutlookReadEmailsNode(VisualNode):
    """Visual representation of OutlookReadEmailsNode."""

    __identifier__ = "casare_rpa.office"
    NODE_NAME = "Outlook Read Emails"
    NODE_CATEGORY = "office_automation/outlook"
    CASARE_NODE_MODULE = "office"

    def __init__(self) -> None:
        """Initialize Outlook Read Emails node."""
        super().__init__()
        # Widgets auto-generated by @node_schema decorator

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_exec_output("exec_out")
        self.add_typed_output("emails", DataType.LIST)
        self.add_typed_output("count", DataType.INTEGER)
        self.add_typed_output("success", DataType.BOOLEAN)


class VisualOutlookGetInboxCountNode(VisualNode):
    """Visual representation of OutlookGetInboxCountNode."""

    __identifier__ = "casare_rpa.office"
    NODE_NAME = "Outlook Get Inbox Count"
    NODE_CATEGORY = "office_automation/outlook"
    CASARE_NODE_MODULE = "office"

    def __init__(self) -> None:
        """Initialize Outlook Get Inbox Count node."""
        super().__init__()
        # No config properties - outputs only

    def setup_ports(self) -> None:
        """Setup ports."""
        self.add_exec_input("exec_in")
        self.add_exec_output("exec_out")
        self.add_typed_output("total_count", DataType.INTEGER)
        self.add_typed_output("unread_count", DataType.INTEGER)
        self.add_typed_output("success", DataType.BOOLEAN)


# Database Nodes
